# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import streamlit as st
from streamlit.logger import get_logger
import numpy as np
import pandas as pd
from sklearn import preprocessing
import lightgbm as lgb
import pickle

LOGGER = get_logger(__name__)

lgb_model = lgb.Booster(model_file='model.txt')

mean_prices = pd.read_csv('./encoders/mean_price.csv')
encoder_mark = pickle.load(open('./encoders/enc_mark.pkl', 'rb'))
encoder_model = pickle.load(open('./encoders/enc_model.pkl', 'rb'))
encoder_equipment = pickle.load(open('./encoders/enc_equipment.pkl', 'rb'))
encoder_place = pickle.load(open('./encoders/enc_place.pkl', 'rb'))
encoder_dict = {'mark': encoder_mark, 'model': encoder_model, 'equipment': encoder_equipment, 'place': encoder_place}

features = ['mark', 'model', 'year', 'equipment', 'mileage', 'place',
                  'description', 'accident', 'mean_price', 'engine_power']
     

def run():
    st.set_page_config(
        page_title="project",
        page_icon=":car:",
    )

    st.write("# привіт! \n # протестуйте модель для передбачення вартості авто :car:")

    mark = st.selectbox('Марка', sorted(['Opel', 'BMW', 'Hyundai', 'Audi', 'Mercedes-Benz', 'MG',
       'Land Rover', 'Volkswagen', 'Tesla', 'Hyster', 'International',
       'Honda', 'JCB', 'Zeekr', 'Skoda', 'Mitsubishi', 'Toyota',
       'Renault', 'Mazda', 'Iveco', 'Peugeot', 'Kia', 'Lexus', 'Fiat',
       'Ford', 'Porsche', 'Nissan', 'MAN', 'Caterpillar', 'Volvo',
       'Comet', 'Yamaha', 'Triumph', 'Manitou', 'Chery', 'SEAT',
       'Van Hool', 'BYD', 'Chevrolet', 'Acura', 'DAF', 'Jeep', 'Dodge',
       'Citroen', 'Schmitz Cargobull', 'MEGA', 'Subaru', 'Jaguar',
       'Suzuki', 'Lincoln', 'Infiniti', 'MINI', 'Changan', 'Scania',
       'Cardi', 'ПАЗ', 'Haval', 'Jetour', 'ВАЗ / Lada', 'Cenntro',
       'Shineray', 'SsangYong', 'ЗАЗ', 'Daewoo', 'GMC', 'ГАЗ', 'Cadillac',
       'Smart', 'Bodex', 'Reisch', 'Dacia', 'Kawasaki', 'STAS', 'Ram',
       'Simatra', 'Grove', 'Krone', 'Sumitomo', 'Linde', 'Chaparral',
       'Alfa Romeo', 'BRP', 'Samsung', 'Geely', 'Demag', 'LDS',
       'Aston Martin', 'Kogel', 'КамАЗ', 'Harley-Davidson', 'Kempf',
       'OMT', 'Chrysler', 'Azimut', 'TCM', 'Fruehauf', 'Bentley',
       'Liebherr', 'BMW-Alpina', 'Lifan', 'Hitachi', 'Богдан', 'Maserati',
       'Kubota', 'PrinceCraft', 'Bobcat', 'Schwarzmuller', 'TuningTown',
       'Rover', 'Bavaria', 'Great Wall', 'JAC', 'TATA', 'Buick', 'Zaslaw',
       'Magyar', 'PPM', 'ЗИЛ', 'BRIG', 'Maxus', 'Schmitz', 'GRAS',
       'Wielton', 'Victory', 'Inter Cars', 'Dapa', 'Xpeng', 'УАЗ',
       'Merker', 'ПГМФ', 'Weber', 'Geon', 'Москвич/АЗЛК', 'Indian',
       'Rover Boat', 'Benalu', 'Tisvol', 'МАЗ', 'General Trailers',
       'Tatra', 'Ducati', 'XCMG', 'STRASSMAYR', 'SANY', 'Kato', 'Ravon',
       'Daihatsu', 'Rivian', 'Polaris', 'KTM', 'Shelf', 'Sennebogen',
       'Львовский погрузчик', 'Polestar', 'Maxxter', 'Leapmotor',
       'Pacton', 'Komatsu', 'ЛуАЗ', 'Kovi', 'Voge', 'Gonow', 'DS',
       'Meusburger', 'Lamberet', 'ИЖ', 'Genesis', 'Panav', 'Trailor',
       'Hobby', 'Howo', 'Ricoe', 'Cupra', 'CFMOTO', 'Fiori', 'КрАЗ',
       'Case IH', 'Stokota', 'ADR Trailers', 'Hyosung', 'БАЗ', 'Scion',
       'Dongfeng', 'Fliegl', 'BT Toyota', 'JLG', 'Bajaj', 'Finval', 'CMT',
       'Wilcox', 'Renders', 'StreetScooter', 'ZX', 'Shacman', 'Samro',
       'Bayliner', 'SCHMIDT', 'United Trailers', 'Isuzu',
       'Lord Munsterland', 'Buster', 'ГКБ', 'Jungheinrich', 'Tadano',
       'Compact Truck', 'LAG', 'L.A.G.', 'Rydwan', 'Ackermann-Fruehauf',
       'Powerboat', 'Langendorf', 'LMC', 'Hummer', 'Niewiadow', 'King',
       'Avatr', 'Carnehl', 'Neoplan', 'ПАВАМ', 'Jamnil', 'Spitzer',
       'Lacitrailer', 'Pragmatec', 'Prod Rent', 'Menci', 'Weightlifter',
       'Nobac', 'DON BUR', 'Boro', 'Pizzaoli', 'Pezzaioli', 'Wormann',
       'САЗ', 'Janmil', 'Feldbinder', 'Pontiac', 'Novatrail', 'Voyah',
       'ALEKO', 'Kelberg', 'Broshuis', 'Nursan', 'Groenewegen', 'Mercury',
       'Урал', 'FAW', 'Aiways', 'Berthoud', 'Caravelair', 'Kobelco',
       'Goldhofer', 'Robuste', 'Fendt', 'Atlas Copco', 'Crownline',
       'Doosan', 'Eriba-Nova', 'Nysa (Ниса)', 'Nooteboom', 'Speed Gear',
       'Кастом', 'Neta', 'ПГ', 'Fisker', 'Changhe', 'Zovko', 'Hatz',
       'Weltmeister', 'Burg', 'CIMC SilverGreen', 'KH-KIPPER', 'Wacker',
       'Ferrari', 'Meierling', 'Jumbo', 'H&W', 'Купава', 'Legras',
       'Setra', 'SWIFT', 'Merlo', 'Knott', 'Oki Boats', 'Ursagroup',
       'Dennison', 'Alpha', 'Wecon', 'Schwingenschlogel', 'ЧМЗ', 'Santi',
       'Trailer', 'MAFA', 'Navigator', 'СhargeDay', 'Yema', 'Hamer',
       'BAIC', 'Forte', 'HKM', 'Faun', 'P&H', 'Protey', 'Like.Bike',
       'De Alm', 'SDLG', 'Bailey Pagent', 'Dethleffs', 'Adria', 'РУТА',
       'BSLT', 'Temared', 'Neumeier', 'Floor', 'Silvatec', 'Terex',
       'Chereau', 'Sprite', 'Bailey Discovery', 'Abbey', 'Tang',
       'Tabbert', 'Ataman', 'TA-NO', 'Takeuchi', 'Vocol', 'Dadi', 'Hamm',
       'MOL', 'Jawa (ЯВА)', 'Elan', 'Coder', 'Atlantic', 'Ammann', 'Wilk',
       'ATM', 'Feber', 'Claas', 'EKW', 'Dieci', 'Rolls-Royce',
       'NFP-Eurotrailer', 'KIP', 'Koluman', 'Hangler', 'Днепр (КМЗ)',
       'Spark', 'Rider', 'Moto-Leader', 'Comman', 'Kayo', 'Loncin', 'BSE',
       'Hisun', 'Segway', 'TVS', 'Kv', 'Tekken', 'Linhai', 'Yadea', 'Sym',
       'Mikilon', 'TGB', 'Zontes', 'Cf moto', 'Electromoto', 'SDC',
       'Balkancar', 'Tracker', 'Solifer', 'Eduard', 'Musstang',
       'MAG Trailer', 'Defiant', 'Moto Guzzi', 'Qingqi', 'Parsun',
       'Adventure', 'New Holland', 'Кияшко', 'Kaiser', '2ППС', 'Bulthuis',
       'San Boat', 'Benelli', 'Haulotte', 'Trouillet', 'Westfalia',
       'Broddson AB', 'Saab', 'НПП Палич', 'Ranger', 'Mueller-Mitteltal',
       'ABG Titan', 'Noblelift', 'Wirtgen', 'Bandit', 'Vermeer',
       'Wartburg', 'Piaggio', 'Bomag', 'YiBen', 'Combilift', 'Lunar',
       'Fiat-Hitachi', 'Atlas', 'КЗАП', 'ENERCO', 'York', 'RIB Альбатрос',
       'ХТЗ', 'МТЗ', 'Gromex', 'Кремінь', 'Hidromek', 'Kinlon', 'Krebs',
       'СМЗ', 'ОДАЗ', 'WorldCat', 'Sukov', 'FG Wilson', 'Kanuni', 'ЧМЗАП',
       'Фермер', 'Plymouth', 'Vogelzang', 'SkyBike', 'Sabur', 'Sam',
       'Austin', 'Berger', 'Южанка', 'Саморобний', 'Viper', 'Alfa', 'Ока',
       'Kolibri (Колибри)', 'Sommer', 'Zremb', 'ТОВ Трактор', 'СЗАП',
       'Автобан', 'Citycoco', 'TR-AX', 'Arctic cat', 'Kassbohrer',
       'Al-ko', 'Ось', 'Delta', 'ATV', 'GRAND', 'Kumlin', 'Generic',
       'TVS2', 'VDL', 'Bockmann', 'К4', 'ЮМЗ', 'SkyMoto', 'YCF',
       'Континент', 'Micansan', 'WeRidEV', 'Geusens', 'Desot', 'Humbaur',
       'Корида Тех', 'SACIM', 'Hornet', 'Dogumak', 'ДТЗ', 'Карпатець',
       'AUREPA', 'Zongshen', 'Tiger', 'Rothdean', 'Besttrailers',
       'Exdrive', 'Крим', 'ЕХО', 'Причеп', 'WM Meyer', 'Four Winns',
       'IFA (ІФА)', 'Ретро автомобілі', 'Прогресс', 'Ditch Witch',
       'Maisonneuv', 'Electric Scooter', 'Мінськ', 'Ellinghaus',
       'Yokomoto', 'NIO', 'Wiola', 'Alesin', 'Senke', 'Kymco',
       'Street food', 'Sanyou', 'SDMO', 'Putzmeister', 'Silver',
       'Autosan', 'Moeslein', 'Gala', 'Tige Boats', 'Glastron', 'Stim',
       'Восход', 'Тула', 'Mobility Ventures', 'Otokar', 'Knapen', 'ЧТЗ',
       'Jonway', 'Муравей', 'Aprilia', 'Fit-Zel', 'Beta', 'Leader',
       'Reinell', 'Lancia', 'Argo', 'Glowacy', 'Alfamoto', 'Soul', 'РАФ',
       'System Trailers', 'Oztreyler', 'Barkas (Баркас)', 'Дніпро',
       'Energy', 'Ackermann Fruehauf', 'Fada', 'Yanmar',
       'Українська мрія', 'Wilex', 'Shuanghuan', 'Hendricks', 'Husqvarna',
       'Сантей', 'Thompson', 'BOS', 'Амур', 'SouEast', 'Zubr', 'Komplet',
       'Sparta', 'Samand', 'Landwind', 'Fluid', 'ППЦ', 'Korten', 'Hussar',
       'ММЗ', 'Колибри', 'AIMA', 'Saturn', 'Багги', 'Gaelix', 'ПТС',
       'Smokercraft', 'Jeanneau', 'Rolfo', 'LeciTrailer', 'Sky Country',
       'Днепр', 'Bailey Pageant', 'MYBRO', 'Meridian', 'Pit bike',
       'Chana', 'Дорожник', 'Futong', 'Malaguti', 'Zorzi', 'Ладога',
       'Genata', 'КрКЗ', 'Ova', 'Motoland', 'Hongda', 'Bashan', 'Торгмаш',
       'ПР', 'Meiller', 'Daelim', 'Sinan', 'FurSeal', 'Evinrude', 'Shark',
       'Wellboat', 'SOR Iberica', 'Sylvan', 'Maybach', 'Rodman', 'Kazuma',
       'Temsa', 'Atlant-Boat', 'Dynapac', 'BMW Marine', 'LDV', 'Ginaf',
       'Trebbiner', 'Yale', 'ЭТЦ', 'Maxum', 'Mariah', 'Princess', 'IHI',
       'Gas Gas', 'Gilera', 'Hongqi', 'SRM', 'ЛАЗ', 'UMS', 'Буран', 'Лев',
       'Denza', 'КШП', 'Powerscreen', 'Keestrack', 'Montracon', 'Indox',
       'Foton', 'Beneteau', 'HBM-nobas', 'Xiaomi', 'Plandex',
       'Brian James', 'Ace', 'Genie', 'Still', 'G-max', 'Sakai',
       'КБ / БК', 'Simex', 'Dressta', 'Abarth', 'Borex ( БОРЭКС*)',
       'Doll', 'Potain', 'Zasta', 'HIAB', 'SEM', 'Hammer', 'МоАЗ', 'CAMC',
       'Linden', 'Neuson', 'Nimbus', 'Ferretti', 'Sea Ray', 'Starcraft',
       'ЕО', 'Rohr', 'ПРТ', 'Galeon', 'ДЗ', 'МЖТ', 'BOVA', 'Freightliner',
       'Казанка', 'Monza', 'Ahlmann', 'Skyjack', 'ИМЗ (Урал*)', 'Hanteng',
       'ПП', 'Willig', 'Geeli', 'Wackenhut', 'Auto Moto', 'Patriot',
       'Everlast', 'Sea', 'Alga', 'МКМ', 'Metso Minerals', 'Бобер', 'O&K',
       'DB', 'Zeppelin', 'Kverneland', 'ТВЭКС', 'РДК', 'Carmix',
       'Stinger', 'VEGA', 'ХАЗ (Анторус)', 'ABM', 'FUQI', 'Krukenmeier',
       'Monterey', 'Mustang', 'Asia', 'MasterCraft', 'Campion', 'A.C.M.',
       'Sinski', 'Iran Khodro', 'FAW Bestune', 'Horse', 'Alpine',
       'VS.Mont.Sro', 'Moffett', 'Merceron', 'Big Bear Choppers',
       'Дністер', 'EOS', 'Bumar', 'TARO', 'ODES', 'Avento',
       'Turbo`s Hoet', 'АМС', 'Klaeser', 'Ventus', 'ВАРЗ', 'Hunter',
       'Brenderup', 'Coachworks', 'Adige', 'Metaco', 'Volta', 'Everun',
       'Москва', 'King Long', 'Tirsan', 'Simson', 'Acerbi', 'Keeway',
       'Bartoletti', 'XGMA', 'Case Construction', 'ХТ', 'AM',
       'Energy Power', 'Orix', 'John Deere', 'Big dog', 'Sinotruk',
       'Boratas', 'Denago', 'Sinomach', 'Yamasaki', 'ЗИМ', 'Shaolin',
       'Royal Enfield', 'Mirofret', 'Fleetwood']))
    model = st.selectbox('Модель', [None] + sorted(['Astra', 'X5', 'i40', '3 Series', 'A6', 'Q7', 'GL-Class', '4',
       'Marvel R', 'Q5', 'Discovery', 'X6', 'Touareg', 'Sprinter',
       'Passat', 'Model 3', 'H 1.6 FT', 'IH', 'e-tron Sportback',
       'e-tron', 'GL 1800 Gold Wing', '535-125', 'R nineT', '001',
       'G-Class', 'Octavia', 'Outlander', 'ID.4 Crozz', 'A4', 'RAV4',
       'E-Class', 'Camry', 'Master', '3', 'Q8', 'M4', 'Daily груз.',
       'CX-5', '308', 'Kodiaq', 'Transporter', 'Tiguan', 'Golf',
       'Sportage', 'ZS EV', 'X3', 'LX', 'Megane', '5 Series', 'Golf GTI',
       'Land Cruiser Prado', 'Superb', 'Doblo', 'M-NV', 'Model Y',
       'Focus', 'Cayenne', 'S-Class', 'Model S', 'Veloster', 'GLS-Class',
       'Juke', '6', 'Leaf', 'Jetta', 'TGA', 'ES', 'Range Rover', '428',
       'Macan', 'FH 13', 'Vito', 'Supremo', 'Tenere', 'Grand Scenic',
       'X5 M', 'GLE-Class', 'Kangoo', 'Bonneville', 'Q8 e-tron',
       'A7 Sportback', 'Insignia', 'A6 Allroad', 'Ducato', 'Touran', 'S4',
       'Lancer', 'Rogue', '1235', 'Tourismo', 'Tiggo 4 Pro', 'Premium',
       'Ateca', '7 Series', 'T916 Astron', 'Song L', 'RX', 'Santa FE',
       'A5', 'Crafter', 'Song Plus Champion', 'Espace', 'A3', 'GX', 'X4',
       'Trafic', 'Accent', 'Arteon', 'M-Class', 'Kuga', 'Bolt EV',
       'Outlander XL', 'ID.4', 'Zoe', 'Sonata', 'X7', 'CR-V', 'RDX',
       'Tucson', '3008', 'EQC', 'Duster', '02-8FDF', '02-8FGF15',
       'XF 106', 'F-150', 'Caddy', 'Qashqai', 'Mondeo', 'XF 105',
       'Pajero Sport', 'ID.6 Crozz', 'Song Plus', 'Sorento', 'Highlander',
       '3CXSM', 'e-Golf', 'Panamera', 'Grandland', 'Aveo', 'Optima',
       'GLC-Class', 'Partner', 'Cherokee', 'GS', 'eNS1', 'Land Cruiser',
       'Multivan', 'CC / Passat CC', 'Karoq', 'TGX', 'Range Rover Sport',
       'V50', '5008', 'E-Tharu', 'Caliber', 'V-Class', 'Fusion', 'Fabia',
       'Model X', '5 Series GT', 'Mokka', 'C4', 'Ranger', 'XC40', 'Q3',
       'Kimo', 'Talisman', 'XC90', 'Laguna', 'Niro', 'Kadjar', 'S-Max',
       'Grand Cherokee', 'SCB S3T', '02-7-FGF-15', 'Kamiq', '4 Series',
       'Eos', 'Edge', 'SKO 24', 'Note', 'MNL', 'C-Elysee', 'Combo Life',
       'Forester', 'Scenic', 'I-Pace', 'Compass', 'TLX', 'C-Class',
       'Crossland', 'Proace Verso', 'C5 Aircross', 'V60', 'SQ5', 'Vitara',
       'MKC', 'Tiggo 7 Pro', 'Avensis', 'SQ7', 'Jumper', 'Elantra',
       'Q4 e-tron', '5', 'I3', 'GLA-Class', 'FX 35', 'Discovery Sport',
       'Hatch', '18.480', 'Fiesta', 'TGL', 'Land Cruiser 300',
       'Combo Cargo', '2008', 'Auris', 'A8', 'Hunter',
       'Range Rover Velar', 'X-Trail', 'R 1200GS', 'XC60', 'Renegade',
       'XF', 'HS', 'C-HR', 'Journey', 'Corolla Cross', 'A-Class',
       'Tiggo 8', 'Magnum', 'Accord', '3 Series GT', 'CLA-Class',
       'Staria', 'Jumper груз.', 'Kona', 'Grand Vitara', 'Pajero Wagon',
       'Uni-K', 'T2', 'Irizar', 'Passat Alltrack', 'Escape', 'L 200',
       'Polo', 'Cruze', 'iX', 'Kona Electric', '1 Series', '39S3', 'X1',
       'Legacy', 'Vectra', 'Vivaro', 'Wrangler', '533-105', 'Landtrek',
       'Stonic', 'S-Cross', 'Doblo пасс.', 'Cargobull', 'Venza', 'FG',
       'NX', 'Zafira', 'Jimny', '4234', 'ZS', 'Ceed',
       '4 Series Gran Coupe', 'Tipo', 'Outback', 'K5', 'Cayenne Coupe',
       'DS5', 'V40', 'CLS-Class', 'A4 Allroad', 'B-Class', 'ASX',
       'Durango', 'S60', '508', 'RAV4 PHEV', 'CX-90', 'H6 HEV',
       'Berlingo', 'Ceed SW', 'HR-V', 'CX-30', 'S90', 'X70', 'TIIDA',
       'Clio', 'H6', '2107', 'Teana', 'Pajero', 'Transit',
       '2 Series Gran Coupe', 'Ioniq', 'Explorer', 'Tiggo 2 Pro',
       'Logistar 200', 'F-Pace', 'Ioniq 5', 'Ariya', 'LT', 'Q50', 'MDX',
       'Movano', 'Micra', 'MKZ', 'Venue', 'Elcrosso 400', 'Clubman',
       'Musso', 'Civic', 'Pathfinder', 'Qashqai+2', 'Lanos', 'C3',
       'Captur', 'SX4', 'F 800ST', 'Patriot', 'Express', 'IS', 'EQE',
       '541-70', 'X6 M', 'i10', 'Eclipse Cross', 'Jetour X70',
       'Q5 Sportback', 'Equinox', 'Nexia', 'Volt', 'Range Rover Evoque',
       'Atlas', 'Koleos', 'Sentra', 'e-tron S', 'Terrain', 'One',
       'Lacetti', 'Boxer', '3302 Газель', 'XF 95', 'CX-3', '18.440',
       'Magentis', 'i30', 'Leon', '2112', 'QX50', 'Golf Plus', 'CX-60',
       'Escalade', 'Hilux', 'Fortwo', 'Mokka-e', 'Cordoba', 'SQ8',
       'Corolla Verso', '2 Series', 'KIS 3W-A', 'Yeti', 'Getz',
       'Challenger', 'XC70', 'Q8 Sportback e-tron', 'Amulet', 'C-Max',
       'Taycan', 'Patrol', 'Axor', 'A1', 'X2', 'TGS', 'Rogue Sport',
       'Ignis', '2171 Priora', 'Sandero StepWay', '206', 'Vario', 'CX-7',
       'XE', 'Dokker', 'Berlingo пасс.', 'Meriva', '4Runner', 'QX60',
       'MT 1440', 'SK', 'Atego', 'CX-9', '2110', 'Rapid', 'RHKS-35',
       'C3 Picasso', 'Murano', 'ix35', 'Nemo', 'Majesty', 'Mustang',
       'Logan', '4008', 'Versys 650', 'Avalon', 'Corolla', 'RS4',
       'Altea XL', 'Tacuma', '531-70', '35S13', 'SA 336K', 'M8', 'Q70',
       '408', 'Defender', 'Sequoia', 'Yaris', 'RS5', 'Tang',
       'Tiguan Allspace', '1500', 'Actros', 'Captiva', 'LN-Series', 'G',
       'MLT 731 LSU', 'Q60', 'EcoSport', '520', 'Beetle', 'Crosstrek',
       'Rifter', 'M6', 'Impreza', 'CS 55 Plus', 'CS 35 Plus', 'Enerco',
       '2121 Нива', 'RZ', '2106', '2104', 'Soul', 'CL-Class',
       'Countryman', 'Grand Musso', 'Sens', 'Transit Connect', '323',
       'GMK', 'Freemont', 'Sandero', 'C4 Picasso', '1118 Калина', 'SD',
       'GLE-Class Coupe', 'H 30D', '7FB10', 'H', '02-8FGF25', 'H 1.8FT',
       'Colt', 'Signature', 'H 40D', '1103 Славута', 'Combo',
       'Outlander Sport', '6 Series Gran Coupe', 'Stelvio', 'bZ4X', 'RC',
       'Grandeur', 'Aqua', '2115 Samara', 'Verso', 'T-Roc', 'Arona',
       'Express Van', 'MidNight Star', '21099', 'Sienna', 'Spark', '207',
       'Nubira', 'SM6', 'Korando', 'Tiggo 4', 'QX70', 'Pilot', 'Jolion',
       'Proace City', 'CF', 'CX-50', 'Coolray', 'EQE SUV', 'Tiggo',
       'Fluence', 'Picanto', 'S7 Sportback', 'Tipo Cross',
       'Transit Courier', 'G 650X', 'AC', 'Sharan', 'Octavia Scout',
       '307', 'Twingo', 'SDP 27', '500', 'NG', 'DB12', '21214 / 4x4',
       'FH 12', 'Bronco Sport', 'SN 24', 'Freelander', '5511', 'Prius',
       'Cerato', 'Insight', 'R 420', 'C-Crosser', '8FGL18',
       'Xsara Picasso', '2109', '7FG15', 'CF 85', 'A5 Sportback', 'ID.3',
       'Focus C-Max', 'VRSCD Night Rod', '500e', '6 Series GT', 'SKM',
       '3SCO1', 'C40 Recharge', 'Sprinter груз.', 'Yaris Cross', 'А08',
       'SAF', 'Carisma', '80', 'C4 Cactus', 'Legend', 'e-NV200', 'QQ',
       'ZR-V', '200', 'Taurus', 'Niva', 'Master груз.', '2111', 'Orlando',
       'EV6', '68', 'GLB-Class', 'Matiz', 'Omega', '2114 Samara', 'Corsa',
       'Expert', '2170 Priora', 'Transit Custom', '2103', 'R 1150GS',
       'Jazz', 'Stralis', 'Escort', 'Terrano', '3CX Super', '26.412',
       'SO1', 'QX56', '2101', 'V90 Cross Country', 'Bolt EUV', 'Roomster',
       'ATS', 'EuroCargo', 'S80', 'GLC-Class Coupe', 'UX', 'Maxima',
       '536-60', 'Jumpy', '807', 'Scorpio', 'Seagull', 'Tiggo 2',
       '18.430', '10.163', '2102', 'Vida', 'E-Pace', 'Kiss 33', 'T-Cross',
       'Xedos 9', '18.410', 'FD', 'Golf R', 'CK-2', 'Rio', 'Toledo',
       'MX-30', 'Camaro', 'Modus', 'EX30', 'H6 GT', 'Fiorino Combi',
       'Ducato груз.', 'RS Q8', 'C1', 'Primastar', 'Swift', 'Epica',
       '208', 'CBF 600S', 'CB 400X', 'Monjaro', 'C4 X', 'Bentayga',
       'Caravelle', 'R 450', 'Pacifica', 'Kadett', 'Boxer груз.', 'GTX',
       'Signum', '124', 'LTM 1030', 'LTM', 'Almera', 'P 6820D ABG', '626',
       'Blazer', '100', 'Crosstour', 'Grand Santa Fe', 'i30 Wagon',
       'Citan', 'iX3', 'Felicia', 'B4 Gran Coupe', 'Doblo Panorama',
       'Logan MCV', 'Gentra', '320', 'ZX', 'S6', 'Scudo', 'LS', 'TSX',
       'Z 1000SX', 'Grand C4 Picasso', 'Punto', 'FX 37', 'RAM 1500',
       'Tundra', 'T916', 'Carrier', '405', '436', 'Grand C-Max',
       'Charger', 'Giulia', 'CB 600F Hornet', 'S5', 'Forte', 'Levante',
       'XV', 'Panda', 'U', '53229', 'Emgrand 7 (EC7)', '535-95',
       'Platinum SE 176', 'S650', 'Cerato Koup', 'Xedos 6',
       'Mustang Mach-E', '300 S', 'V70', 'March', 'Clarity', 'SPA-3E',
       'Viano', 'Kicks', '500L', 'C8', 'Drag Star 1100', 'B-Max', 'TT',
       'Offroad', 'EX8', 'EX10', 'EQA', 'Logistar 100', 'Tiggo 8 Pro',
       '301', 'Fiorino груз.', 'Scala', 'Doblo груз.',
       'Range T/T-Series ', 'Altima', '407', 'Matrix', '620', 'Virtess',
       'Haval M4', 'JS 370', 'Bora', 'Palisade', 'GSX 1300R Hayabusa',
       'LTD/WAD', 'FJ Cruiser', 'Avante', '883 Sportster Custom',
       '1102 Таврія', 'Express Combi', 'C5', 'MK Cross', 'RX-8', 'JS4',
       'Rio X', 'Spring', 'LPT', 'Antara', 'Tourneo Connect', 'Avenger',
       'Enclave', 'Jaggi', 'VTX 1300S', 'Tiger', 'MK', 'Forfour', 'D 653',
       'NV400', 'TGM', 'MR', 'i20', 'GLK-Class', 'Zafira Tourer', 'X3 M',
       'BSL', 'GTI', 'MB', 'АТТ', 'TGE', 'ММЗ 554', 'AMG GT 4-Door Coupe',
       'S40', 'Amarok', 'S3', 'Megane Scenic', 'ILX', 'Falcon Riders',
       'Mifa 9', 'S 24', 'Lodgy', 'Scenic XMOD', 'Sonic', 'SCS 24/L',
       '2705 Газель', 'SKI 24', 'Frontera', 'FH 16', 'K 1600GT', 'Impala',
       'SL-Class', '2 Series Gran Tourer', 'Q7 e-tron',
       'Intruder 400 Classic', 'HD 78', 'BPW', 'NW', 'Octane',
       'Versa Note', '55102', 'Proace', 'P-24', 'G3', 'Magirus',
       'EQS SUV', 'Continental GT', '536/70', 'M3', 'Road Glide', 'Quest',
       'S-01', 'Skywave 400', '469', 'Carnival', 'Rexton',
       'Golf Alltrack', 'Crane', 'M2', 'M 300', 'Ascent', 'CLK-Class',
       '500X', 'Yuan Plus', '8315', '911', 'Galant', 'RS7 Sportback',
       'EQB', 'Midlum', 'Kiss', 'R 480', 'QX80', 'ix55', 'NC 750XA',
       '3110 Волга', '1102 Таврія-Нова', 'Bluebird', '6 Series', 'QX55',
       'S510', 'Pro Series', 'SRX', 'Dart', 'M35', 'V-Strom 650',
       'Electric', 'R 380', 'G37', 'EQS', 'CK', 'FR-V', 'Boxster',
       'Carens', 'Tribeca', 'MLT 735-120 LSU', 'MLT 634-120 LSU',
       '8 Series', 'X-Type', 'Malibu', 'Grandis', 'Tacoma', 'S01',
       'Flying Spur', 'MX-5', 'H-1', 'SCS 24', 'NC 750X', 'CT', 'Q2',
       'L 2000', 'EX90', 'Berlingo груз.', 'Maybach',
       'T6 (Transporter) пасс.', 'Logistar 260', 'Boxer груз.-пасс.',
       'FX 30', 'S 300CX', 'Jog', 'Solenza', 'Commander', 'Nautilus',
       'Ibiza', 'Majesty 400', 'Galaxy', 'Benelli TNT300', 'SLK-Class',
       'R 440', '4007', 'JS 200', 'M5', '2141', 'Vellfire', '3221 Газель',
       'Space Star', 'Scout', '85', 'Aygo', 'Bolt', 'XT4', 'Sephia',
       '26.410', '720R', 'Encore', 'Benalu', 'SVAL', '53366', 'T8',
       'K 1200LT', 'ТХ34', 'А-09202', 'Elara', 'G25', 'Exeo ST',
       'Vivaro груз.', 'JS6', '508 RXH', '815', 'D', 'F-Type',
       'Legacy Outback', 'Hypermotard 1100S', 'R-Class', '6520', '3CX',
       'QY25K5', 'Stream', 'SuperNova', 'SPR', 'LE 12.225', 'LPT 613',
       '605', 'RAM', 'Bencere', 'Symbol', '190', 'Transit пасс.',
       'Profi Liner', 'Cross Polo', 'Qubo', 'Kalos', 'STP', 'SY', 'SN',
       'Safe', 'i4', '848', 'XC40 Recharge', 'Soul EV', 'MK-2', 'FLSTS',
       'KR', 'XM', 'R2', 'Terios', 'R1S', 'RZR', '3307', 'TX 34', '4331',
       '131', 'Bipper', 'i-MiEV', 'TT S', 'R 18B', 'e-208', '21213 Niva',
       'Corvette', 'F3', 'Linea', '31105 Волга', '107', 'F 800S',
       'Enduro EXC-F 500', 'Evanda', 'G345PE', 'G342PE', '825M',
       'CBR 1100XX', 'GХ2', 'R 230', 'FM 9', 'RXP-X', 'C-Zero', '5440',
       'X4 M', 'Drag Star 400', '2108', 'Sedona', '1111', 'LC', 'M37',
       'KP 250', 'Maverick X3', '2', '2172 Priora', 'Passport', 'Neos II',
       'C11', '130', 'GTR 1400', 'EX 35', 'T3-011', 'Grand Espace',
       'Road Glide Special', 'Odyssey', 'Navara', 'FT', 'C70', 'FM 12',
       'FXFB', 'SGF S3', 'XCeed', '159', 'TDM 900', 'Bravo', 'Sierra',
       'Vino', 'Tourneo Custom', 'Tigra', 'Yukon', 'Tiggo 7', '2105',
       'GS 500E', 'Envision', 'Favorit', 'FLHXSE', '969М', 'RAV4 EV',
       '406', '250 Lite 4T', '2113 Samara', '300 Rally', 'ТХ', 'Fiorino',
       'Primera', '250', '1119 Калина', '412', 'i7', 'Shuttle', 'Jetstar',
       'Voleex C30', '7 Crossback', 'MCS 3', 'Optiliner',
       'Termo King SMX', 'Espero', 'Юпітер 5', 'Q5 e-tron', 'XG 750',
       'G80', 'Splash', 'Kyron', '27175', 'XRay', 'C6', 'S8',
       'Heritage Softail', 'TF34C1', 'Territory', 'G35', 'NV35PK',
       'Grande Punto', 'S383EL', 'SVKT 24P', 'Grandland X', '53213',
       'A15', 'Ascona', 'C-Series', 'Thalia', 'QX30', 'ZZ', '901',
       'Almera Classic', 'LPT-22', 'Ampera-e', 'L', '390 Duke',
       'Panigale V2', 'Clarus', 'Alum', '607', 'А-09212', 'SCS', '806',
       'MT-07', '2752 Соболь', 'Dyna', 'Ridgeline', '4CX', 'QM6', 'iOn',
       'UGD', 'CForce 400AU-L EPS', 'e-Lavida', 'Lupo', 'Diavel',
       '2 Series Active Tourer', '5432', 'Ryker', 'Transtar', 'Fit',
       ' iX1', 'V40 Cross Country', 'DB', 'T1', '3577', '1300 S',
       'Bullet', 'WX', 'VT 750C', 'FXDRS', 'F 2000', 'Gladiator', 'Jimmy',
       'Veracruz', 'S 2000', '18', '24.362', 'Sportster', 'Emgrand X7',
       '3NC38', 'CTS 4', 'MK-Series', 'Sirion', 'GT 650R', 'А 079 Эталон',
       '8085', 'VFR 1200F', 'R nineT Scrambler', 'EC 220DL', 'CBR 1000F',
       'Roadmaster', '428E', 'C-HR EV', 'Coupe', 'Integra', 'tC',
       'CVO Street Glide', 'Road King', 'E11K', 'MKX', 'SDS 350',
       '1117 Калина', 'Faze 250', 'Xsara', '31514', '544008',
       'Hypermotard 796', 'Scrambler', 'Traveller', '69', 'Up', '53215',
       'MT 1030ST', 'C3E', '3246ES', 'LE 8.140', '1199 Superleggera',
       'ER-6N', 'G 310GS', 'Dominar D400', '147', '505', '550',
       'Scirocco', 'KX 71-3', 'PT Cruiser', '8035', 'ID.5', 'CB 400SF',
       'W25-50', 'NW 3', '16.370 пас', 'D5', 'Alloy', 'Demio', 'ROC',
       'Work', 'LandMark', 'SX', 'RS3', 'F 700GS', '18.220', '926',
       'Convertible', 'Clio Symbol', 'FZ6 Fazer', 'T-Max 500', 'M25',
       'VFR 1200X Crosstourer', 'Atlas Cross Sport', '5434', 'SR 334',
       'FZS 600 Fazer', 'Enyaq iV', 'KIS', 'Dio AF-34', '451',
       'Expedition', 'Trax', 'Bowrider', '8FBET16', 'NC 700XA',
       'Ninja ZX-14R', '804277', 'EX 25', 'NQR', 'Actyon', 'Impreza WRX',
       'Formentor', 'ID.4 X', 'J5', 'FLHX Street Glide', 'GS 500',
       'Land House', '300M', '330', 'PD', 'XRV 750 Africa Twin', 'DS3',
       'RXT-X', 'KIS 3W-S', '31512', 'S 1000R', 'IQ', 'Agila', 'StreetKa',
       'CRF 300L', 'Traverse', 'Safrane', 'V60 Cross Country',
       'Continental', 'RS6', 'CRF 250L', 'Super Salon', 'B12', 'Suburban',
       '33', 'VTX 1800R', 'BPW eco', 'C3 Aircross', 'NC 700S', '914',
       'Puma', 'Navigator', '1982', 'SMFF', 'LE 8.150', 'Kandi EX3',
       'SPC', 'JC', 'Fazer', 'ZX 9R', 'CTS', 'ESE', 'GT 250R', 'FX',
       'R 500', 'XCT 25', 'S 450', '300C', 'Impreza WRX STI', 'Dashing',
       'Vito груз.', 'Vito пасс.', 'Dargo', 'LBX', 'A18C3F',
       'T6 (Transporter) груз', 'Caddy груз.', 'Arteon Shooting Brake',
       'LF', '26.480', 'Ghibli', 'Altea', 'C4 Aircross', 'AMG GT', 'SDS',
       'Partner груз.', '211040', 'SA 33-9K', 'ROR', 'SCB', '65111',
       '54329', 'N120', 'N56', 'N200', '401', 'Grecale', 'Kubistar',
       'XC60 Recharge', 'e-C4', 'JS2', 'Sunray', 'JS3', 'J7',
       'Transit груз.', '95', '114', 'LK-Series', 'ZAXIS', '66', 'e-Up',
       'Galloper', 'eNP1', 'Zafira Life', 'Jumpy груз.', 'Tempra',
       'Crafter груз', 'TR', 'CT 2', 'Armada', 'Sylphy', '0-4-44CN',
       'MNW', 'Phaeton', 'SYY3CX', 'Z4', 'Geusens', 'EuroTrakker',
       'B2600', 'Fruehauf', 'Ora 03', 'e-tron GT', 'DBX', 'GT', 'Talento',
       'Carrier Vector', 'ID.7', '452', '5336', 'EC 210B LC',
       'Genesis Coupe', '480', '12.224', 'Integra 750', 'SKS',
       'Lord Royal', 'XJ', 'KIS3B', 'LVFS', 'Fuso Canter', 'R8',
       "Lion's Coach", 'Megane E-Tech Electric', 'XCT 12', 'EX-1',
       'Yudo K3', 'H3', 'Fullback', 'B1430', 'GTL', '12', 'Cool-Maxx',
       '007', 'Cargo', 'Stinger', 'JS 160', 'Acadia', 'CHKS/AH',
       'Taycan Cross Turismo', 'Hover', 'N 1116', 'X', 'MLT 630T',
       'Movano груз.', '8040', 'FM 13', '112213С', 'XT5', 'LE 180',
       '2190 Granta', '929', 'SF', '350', 'Ioniq Electric', 'Ioniq 6',
       'AWE', 'Xantia', '5320', 'Arkana', '11055', '26.460', 'Kerax',
       'Scudo пасс.', '3303', 'SDC 27', 'Mega', '65055', '3E20RD', 'N90',
       'N410', 'N350', 'T6', 'K7', 'Chief Dark Horse', 'SP 24',
       '3 e-Tense', 'Tarraco', 'NZ34.2S-5', 'R 400', 'SA', 'S3S', 'TF34',
       'Geusen', '431410', 'Liana', '8.163', 'Premacy', 'UB', 'PM',
       'Mustang GT', 'BR2', 'i3S', '31', 'SBA', 'Partner пасс.',
       'CBF 1000', '8.180', 'SK-Series', '96-3049', '2700VG', '3507',
       'SR34BT', 'GS-SAF', 'R4', '850', 'KIP', 'GTO', 'Nitro', '8350',
       'R1T', 'Alhambra', 'Element', '4x4 Urban', 'Picnic', 'Euniq 6',
       'MKT', 'Free', 'H2', 'KTZK18', 'SKBT', 'DHKA', 'Han', 'Beat', 'TX',
       '41.414', 'NS34', '35S1701 груз.', 'XD4', 'XB7', 'SDF', 'SCF',
       '300', 'Cool Liner', 'UCC', 'Цементовоз', 'Vox', 'Vaneo', 'CC',
       'HD 120', 'Daily', 'LDV Convoy', 'DS4', '039', '35C13', 'Roadster',
       'Prius Prime', 'SPR 24', 'Grand Marquis', 'SKI', '3309', '4320',
       '01Y', 'Golf GTD', 'GSX 600F', '220', 'Verano', 'X80', '4081',
       'Lanos Cargo', 'Terracan', 'FMX 11', '3570', '6422', '21 Волга',
       'Caravan', 'Stratus', 'Grand Caravan', 'Prestige', 'U5', 'F', '11',
       '26.463', 'Rich 6', 'Brute Force 750', 'Velite 7', 'Tiggo 3',
       'Raptor', 'А 081 Эталон', 'S175', 'Creta', 'Nano Box', 'FT 95',
       '315', 'NV300', '456', 'QY', 'ER-6F', 'САЗ 3507', 'Forza', '1031',
       'Grand Vitara XL7', '303', '26.430', 'Encore GX', 'Colorado',
       'STN', 'Regal', 'GSA', 'SKHL 24', 'A2', '8025', 'Multistrada',
       'CBF 600', 'R 410', 'Kaiser', 'HFC 1020K', '540-140', 'С34',
       '525-60 Hi-Viz', 'SpaceTourer', '26.403', 'Diamant', 'FLHX', 'QAS',
       '437040', 'X70 Plus', '53212', '65115', '2140', 'LE 8.180',
       'DX 225LC-3', 'Mascott', 'Rodius', 'S', '718 Boxster', '108',
       '940', '521', '65C17', 'Euro', 'Genesis', 'Corsa-e', 'Force',
       'Кастом', 'Giulietta', 'Floride', 'SP', 'V', '0-3-38L',
       'LF200-10L (KPT)', '01', '555102', 'Bronco', '3139', 'Scenic RX4',
       'Luxus', 'CB 650R', 'DX', 'Ocean', 'Ideal II', 'TrailBlazer', 'i8',
       'XL 700V Transalp', 'K Series', 'SC20', 'S Series', 'Alphard',
       'Faga MHP', 'EX5', 'Silvergreen', 'SDK', 'Azera', 'Majesty 250',
       'SD22E', 'Vikrant', 'N35', 'Sunny', 'Desert X', '4310', 'FM 11',
       'SKO', 'EQ Forfour', 'SG 03', 'YZF R6', 'N3O', 'Neuson', '7',
       'e-2008', 'F8', 'MSK', 'HFC 1020KR', 'Kizashi', 'TXC', 'DO 240 Z3',
       'Orion', 'SA33-8K', 'Voyager', '24 Волга', 'X200', 'Venga',
       'HWTPAS', 'AN', 'ПГ 02И', 'Pajero Pinin', 'Pegasus',
       'YZF 600R Thundercat', 'P', 'SCB S3B', 'S630', 'T740', 'RL', 'SW',
       'M', 'U55-4', 'S5 Sportback', '18.224', 'Monster', 'Panigale 959',
       'Praktik', 'XC90 Recharge', 'GV60', 'Walking Floor', '26.440',
       'Tiggo 5', 'CB 1000R', 'MPV', 'Light 3', 'S215HD', ' Velite 6',
       'S1', 'FMX 13', '3A-3SHKSE', 'Address V125', 'Clubvan', 'Fairway',
       'F 800GT', 'Q40', 'Boulevard', '166', 'EM26', 'P 40.16K', '544069',
       'Т 713.12', 'A7', 'Q3 Sportback', 'Shuma', 'Alto', 'e-Deliver 3',
       'e-Deliver 9', 'Deliver 9', 'T90 EV', 'Aviator',
       'TurboDaily груз.', 'eQ', 'Barracuda', 'RS Q3 Sportback',
       'Caddy пасс.', '969 Волинь', 'Ram Van', 'FR-S', 'ix20', 'Wingle',
       'Altea Freetrack', 'SZ 336V', 'Кріпиш', 'RCZ', 'АЗПС', '8109',
       'TE 47XS', 'P 75.9 CS', 'SL25A', '18.225', 'Cross Touran',
       'Dio AF-56', 'YM', '390 Adventure', '19.414', 'AWZ', 'E',
       'Jog SA36J', 'CTX 700', 'CMX 500 Rebel', 'Haval H3', '412 ИЭ',
       'СА 3252', 'BR3', 'R 620', 'EQ Fortwo', 'EV5', '75', 'Mii',
       'DST-30L/V2A', 'Seres 3', 'Materia', '370Z', 'KX 057-4', 'EX 650',
       'EQV', 'Proace City Verso', 'Т-130', 'C2', '8328', 'S67S',
       'S-Type', 'TF', 'R 1250GS', '543205', '65117', 'Cayman', 'Eastar',
       'Camry Solara', 'SN24', 'CBR 1000RR', 'Boulevard M109R', 'NV200',
       'Cobalt', 'Gran Move', 'LaCrosse', 'Exclusive', '4505', 'SDR 27',
       'Golf GTE', 'SDC', 'SAK H40 18 73E', 'Mirage', 'Grand prix',
       'Hiace', 'Sportsman 850 EFI', 'Rio X-Line', 'NKR', 'Desperado 400',
       'Kis', 'Jumper груз-пасс.', 'Family-Fish', 'Полуприцеп', 'e-Bora',
       'HD 72', 'Ampera', 'Agriliner', '45144', 'eQ1', '52', 'X-NV',
       'X-Trail 250', 'ZDX', 'QM3', 'QY30K5', 'N 122', 'EU 350', 'CF550',
       'Ibiza ST', 'EC3', 'E-series', 'XJ6', 'Braves 200', 'NSP', '469Б',
       'iEVS4', 'U27-4', 'Fltenburg', 'ATF', '485', '55111', 'Earth',
       '391', 'Almtrawler', 'Dio 110 (JF31)', '5460', 'LG', '650',
       'Quattroporte', 'RPS', 'Flex', '02-8FG25', '19.422', 'New Line',
       '19', 'Cadenza', 'T40170', 'T590', 'S570', 'Dolphin', '90', 'B7',
       '160', '43336', 'Arocs', 'Dreamer', '43362', '4256', 'NMax',
       'Sportsman Touring 570', 'ZWP 180', 'Grand Modus', 'NV', 'TSA',
       '25', 'ST-STC1', '8021/3S', 'Trezia', 'NR', 'CForce 450L',
       'Latitude', 'C 400GT', 'Vulcan', 'G 310R', 'R 18', 'EU260', 'FLA',
       'Skywave 250', 'FL 6', 'Street Glide', 'XL 1200CX', 'RLX',
       'VZR 1800', '3055 Ciera', 'CH 878', 'Mariner', 'W30', 'L 544',
       'MT-09', 'FT 125-K9A', 'XL 1000V Varadero', 'CYY', 'RSBS',
       'Grand Voyager', 'Mark II', 'BFT', 'EC 55C', 'ThermoKing',
       'Lord Ambassador', 'Major', '400', 'Spectrum', 'NS',
       'Actyon Sports', 'Prius v', 'S330', 'ZCS', 'NC 700X', 'Laurel',
       'Comtesse', 'Admiral', '2123 Niva', '3160/3162', 'А09204',
       'Eclipse', 'Midi груз.', 'BDF', 'Fortuner', 'PCX 125', 'MF',
       'Lead 110 JF-19', 'JV', 'EX', 'XL 883N', '18.232', 'Carina E',
       'City K-ZE', 'CT5', 'BI 30', '0-3-36', 'xB', 'City Leading',
       'BW80', 'HD 90', 'Silverado', 'Multistrada 1200S', 'K85F', '695',
       'Anco 24', 'Crossfire', '640', 'Power', '18.540', 'CR', '535-140',
       'Monster 937', 'Intruder 800', 'NW 33S', '31519', 'Taos', 'Sport',
       '655', 'EC 240CL', 'Ninja', 'MLT 845-120 LSU', 'Streetfighter',
       'Elysion', 'AV', 'Deluxe', 'Burgman 200', 'V8', 'SL', 'BL 71',
       'OKS 13-27B', 'Exeo', 'Tercel', 'Solaris', '35 NWBG', 'Tucano',
       '883 Iron', 'JX35', 'Z 650', 'Uoplyst', 'Morning', 'L 580', 'T-76',
       '642508', 'TE', 'F 900XR', 'RS e-tron GT', 'ROC 37 T3B', 'А-069',
       'Tribute', '8018', 'Baleno', 'DB11', '340', 'DP', 'Ghost',
       'RAM 2500', '4371', 'SKA', '965', 'Excellent', '5337', 'Kompakt',
       'W-14 ZGV', 'CBR 600F', 'SDDU27', 'CAR Plus', 'TYP', '416', '427',
       'JS 145', 'Everus VE-1', 'Maverick', '2206', 'Montero', 'T300',
       'ELR', 'KIS 3W', 'LiveWire', 'Avensis Verso', '10-36', 'R1M 250CC',
       'Renegade 250CC', 'ML', 'BWS-R', 'Tao Tao Scrambler', '125', 'JL',
       'CRF', 'Shark', 'LX200AU-2', '300 ATV', 'Pantera', 'LX 700',
       'CRF 450R', 'Snarler', '525ACX', 'Villain SX10', 'AU', '600',
       'Apache RTR180', 'HT', 'XWOLF 300', 'CR6', 'Cross', 'Unit S200',
       'CBR 250', 'Unicorn', 'ATV', 'Apache RTR 160', 'Z', 'Alpha',
       'Scorpion', 'SP 125-7', 'J3D', 'YAMAHA Z210 EFI', 'AU 300', 'T9',
       'AY', 'Bull', 'Orbit', 'Luna', 'Pulsar', 'LH 400ATV-D',
       'Hardy 200', 'RR 250CC', '250 R1M', 'Blade', 'LH300-D EFI Promax',
       'Gear', 'ZT350-T', 'HAWK', 'CForce', 'FZ', 'Tracer', 'Grizzly',
       'MT', 'EM RR', 'EM Panigale Plus', 'EM R3', 'EM Z1000',
       'EM Diavel', 'Spaceback', 'Tank Container', 'A3 Sportback', 'CR-Z',
       '45', 'DV 1792', 'Targa', 'Maxi', 'Prius C', 'CA 1061', 'J2', 'H0',
       'Artic', 'Aerio', 'PL', 'GS 500F', 'NS34ST', 'MT 200-8', 'CR-X',
       '202', 'LS 650 Savage', 'Defiant', 'V7 Racer', 'Global Eagle',
       'Address V100', '20', 'S70', 'Master I M-330', 'Wagon R', 'W',
       'Одиссей', 'S 3803G', 'Boxer 150', 'X-Trail 250 Trophy',
       'GSX-R 750', 'SX 85', 'CityR 200', 'ProCeed', 'SYY', 'XR', 'Tawa',
       'L 300', 'Aurion', 'Solti', 'E16', 'UD', 'MC', 'Ulysse', 'TNT 25',
       'S 2632E', 'HTL', '215', 'ST', 'C31', 'CE 04', 'Westfalia', 'T38',
       'KL', 'E2', 'Terra-X', 'ZZ 50', 'Scandia', '420', 'SR', '110',
       'TD921 Altano', 'SPA', 'F 650CS', '9-5', 'X-Road', 'Z02614',
       'X-Ride', 'Joker 50 AF-42', 'B10R', '621 VS', 'Town Car',
       'Dominar 400', 'TurboDaily', 'CBR 125R', 'Зубренок', '14.222',
       '21251 Комби', 'Q30', 'HD 12', 'Dio AF-35', '226', 'FE3D20N',
       '7T-1', 'W 2000', 'DFL 1250', '24-10 Волга', '2290', 'Compact',
       '418 S', 'W 150', 'LX250-15 CR4', 'G70', 'SMB', '1.3', 'X9',
       'Burgman 125', 'BW', '150', 'DV 70VO', 'EC 380D', 'Combi C',
       '2000LX', 'FH', 'Z 750', '60', 'SP 125C-2X', '32053',
       'GSF 600 Bandit', '9370', '309', '2217 Соболь', 'М20 «Перемога»',
       'Pointer', 'NС', 'SH 125', 'LDN', 'ЕХ', 'Previa', '69A', '91А',
       'YB 150T-15', 'XSR', '2217 Баргузин', 'VT 750 Shadow', 'Regatta',
       'CT6', 'CF625', 'S2', 'MR Wagon', 'bZ3', '2715', 'К 750', '414',
       'Т-25', 'Fruehauh', '312', 'GSR 600', 'JS 220LC', '82.1 Білорус',
       'L3-3500', 'КРД 050108', 'Almera Tino', 'HMK 370 LC HD', 'HMK',
       'ZZR 1400', '1200N Sportster Nightster XL', 'Aerox',
       'Korando Turismo', 'XY', 'Corniche', 'Планета 5', 'Address 110',
       'Trajet', 'Ror', 'Dio AF-27', 'EX5-Z', 'Applause', 'SP 200R-27',
       '25BMH', 'PA', 'Lets 4', 'ZG 1400', 'С-3А', 'Ray', '31029 Волга',
       '8300', '290DC', 'FZ6', '256', 'Arco Agro', 'NP300', 'Motion',
       'Ciera', 'YBR 250', 'Планета 3', 'Fury', '8304', 'Venture', '403',
       '938', 'ПФ-01', 'Acclaim', '827-1', 'N 316', '14.280', '305',
       'CRDX', 'SFV 650', '2EC19', 'X-Road 250CBB', 'LX 300GY',
       'SP 150-S28', 'Z 800', 'KPT', 'SMC 690R', '2194 Kalina', '460',
       'E5', 'KA', '634', 'R 1200C', '002', 'Corsica', '10A', 'N32', '1',
       'FT 200-23', 'Саморобний мото', 'XY 250GY-6C', 'Wind',
       'GSX-R 1100', '9-3', 'KM-300', 'SG', 'Junfeng EK11', '23', 'ADP',
       'Burgman AN 650', 'F5', '3 Crossback', 'PC', '315 HD', 'ДВСШ 16',
       'KPX', 'F2', '855101', 'VT', 'Connect', 'Sintra', 'XC', 'TXD',
       'Blackster', 'Verde 50', 'Tahoe', 'MT 150-8', 'Lancer Evolution',
       'Yuan', 'C30', 'Space Wagon', 'DR-Z 400', '9.9 HP',
       'Lead 50 AF-20', 'S533 WAT', 'Viking', 'EA', 'FT 300', '1105 Дана',
       'ПГМФ', 'TRK', 'VT 400', 'N 117', 'XS', 'CB 750', 'Colt 125',
       'FLHTK Electra Glide Ultra Limited', 'LF 150-13', '815 CL', 'C 1',
       '968М', 'KP 200', 'Maple C82', 'Lets 5', 'Versa', 'Lets 3',
       'V 150P', '1300', '8561', 'Tourliner', 'Саморобний', 'Croma',
       'Trophy', 'Rexton Sports', 'П5-01', 'Drag Star', 'X-Max', 'Ciao',
       'CHKS', 'V 250l', 'Paladin', 'CVO Limited', 'VT 250F', 'ZZR 600',
       'Hornet', 'SP 125C-2C', 'FTR 300', '475', 'S370N', 'Uno',
       '1199 Panigale S', 'XOR', 'Apache RTR 200', 'Tact AF-24',
       'Ambassador', 'AP 50', '250CC', 'AT', '502C', 'SF90', 'Suv',
       'Mint', 'АМГ', 'А-09201 (E-1)', 'Планета 2', 'Sepia 50', '360',
       'VTX 1800C', 'К 750М', '4502', '3909 Фермер', 'Grand Starex',
       'Jog SA16', 'Asia', '93892', 'LX 250GY-3', '50', '960', 'XLR 250R',
       'Iliade', 'SDP 24', 'K113', 'EQ1032', 'SNCO 24', 'Midi пасс.',
       'V0-2512', 'Touring', '2717 Ода', 'XL 1200NS', 'JS 220', 'Eagle',
       'LPG Tank', 'Vespa', 'GSA24', 'Lantra', 'SP 200R-28', 'FJR 1300',
       'Саморобний причіп', 'А-092', 'JR 200', 'G90', 'AG', 'XJR 400',
       'КРД-050110-50', 'SR 200', 'Dakar', 'Terrano II', 'SCX', 'VTZ 250',
       'Albea', '857100-4012', '3153', '32213 Газель', 'R1', 'Sey Mak',
       'Corsair', 'Z 750S', '53', 'ASD', 'CB 500', 'Siena', 'Lets 2',
       'GSX-R 600', '3163 Patriot', 'F 650', '3STD', 'REF', 'Trident',
       'CBR 250R', 'SR 220', 'ПЭА-1.0', '8500', '260', 'TIGER 150',
       'FZ1 Fazer', 'SP 250D-1', 'Brava', '3B', 'Pulsar NS200', '440',
       'Tourneo Courier', 'Carina', 'B-125', 'VN 1500', 'Днепр-11',
       'Intrepid', 'A3AT', 'В22', '856102', 'Cruiser', 'Atom', 'М',
       '99981-02', 'R 1200RT', 'BWS', 'Автоприцеп', 'Emgrand EC7-RV',
       'Vento', 'WM-HL', 'HC', 'Sundowner', 'Camptourist', 'T39',
       'Класичні', '2М', '23.414', 'R 470', '26.360', 'RT', 'PJCTA3',
       'Superb Scout', 'F0', 'AM-S', '19.463', '133 ГЯ', 'LTD', 'SCLS',
       '8355', 'Netam', 'Next', 'W4028 Cruiser 2', '215 HD', 'GT-200',
       'N 1217', '25M Sea Pro', 'SM7', 'HLS', 'WRX', 'S 1000RR', 'D-STA',
       'e-tron S Sportback', 'S385PB', 'HT 250T-3', 'LH 300', 'Dio AF-68',
       'XL 600V Transalp', 'ES8', 'VN 900', 'Grizzly 700 FI', 'GLR 125',
       'A67', 'XY 250GY-6B Enduro', '750', '2120 Надежда', 'W-2',
       'MT 200 Region', 'Gear 4T', '638', 'ММЗ 45021', 'ALX', '424',
       'Rigin', 'CBR 500R', 'CMX 1100DP', 'M11', 'Desert', 'DR 250',
       '1290 Super Adventure', 'Emgrand EV350', '300R', 'Supra',
       'Vulcan 2000', 'CDKS', 'Daily пасс.', 'MXU', 'ПТ-012', 'EC 210CL',
       'PC 210', 'ROBEX', 'SH', 'JS 175', 'BSA', 'KingQuad 750', 'BRZ',
       'A07А I-VAN', 'Celica', '53211', 'Caprice', 'Haval M2', 'Dorado',
       'Chieftain', 'Maxcruz', 'LF 50', 'NRG 50', 'Gemini', 'Opirus',
       'SMR-3', '115BETL', 'Трейлер', 'MT 200-10', 'Fosti 150', '3D0004',
       'Axxess', 'CLC-Class', 'XVS 950', 'R 1300GS', 'FT 250 CKA', 'V420',
       'LF 175-2E', 'Cinquecento', 'RZX', '32054', '185 SF', 'Adria',
       'OmniExpress', 'Econoline', 'Emgrand GSE', 'L22', '250 Lite KT',
       'Street Bob', 'MVT', '6АКЛ', 'Mohave', 'Maxam 250', 'XR 150L',
       'GL', 'XL', 'NT 1100DP', 'CMX 500', 'CB 750 Hornet', 'X-ADV 750',
       'PCX 150', '250 Start', '3M', '1111 Ока', 'ТМЗ', 'Carrier Maxima',
       'STPN', 'Logo', 'Marine', 'Region', '31N5 EU', '8160', 'MV-1',
       '9000', 'Легковой', 'NO', '3 Series Compact', 'XG 750A',
       'XVS 1100 Dragstar', '431412', 'Sultan', 'Crown', 'SPR 24L', 'N31',
       'CBA', 'Largus', 'k100', 'Rekord', 'MT-03', 'Lion City', 'T-MAX',
       'Cuore', '9', 'Inspire', 'Т-170', 'YY', 'М2', 'Sportcity',
       'KLE 500', 'Steed 400 VLX', 'Duo 3500', 'Tracker', 'LX 200-GY3',
       'Leganza', 'H 200', 'NV 35', 'XY 200 Intruder', 'EVO',
       'Electra Glide', 'Dio AF-62', 'X8', '170B', 'Delta', 'AM-310',
       'PC-350', 'Yuan Pro', 'CO', 'Yamasaki', 'Antos', 'SP-150', 'XTS',
       'Country Man', 'K 1200S', 'Invader', 'C', '2203', 'Prelude',
       'Крым', 'S2000', 'А-40162', 'Crossland X', 'Corrado', 'TKS 24',
       'HDR', 'B1000', '210', 'E290', 'Spacy 125', 'S-1', 'YN',
       'Dio AF-18', 'XY 200GY-6C', 'ZF18', 'D33C', 'Pony', 'Eaf', '73',
       '205', 'Storm', 'Boxer X150', 'XV 1700 Warrior', 'R 114',
       'Clipper', 'Damas', 'Scorpion 200cc', '819', 'Pixo', '02-7FGF30',
       'Capri', 'LF150-2E', 'B4-6A', '3B0013', 'PW', 'Leonardo 150',
       '856103', '2142', 'RXP', 'T916 Acron', 'Town & Country', 'SCEO',
       'GSX-S 1000', 'SP 125C-2XWQ', '146', 'Goch',
       'Norden 901 Expedition', 'Nova', 'Prince', 'Trailers', '418-17',
       '9925', '1116', '315195 Hunter', '432', 'Днепр-12', '2500',
       'Carmichael PT44/3', 'Regal TourX', 'TRV 450', 'LX 250GS-2A',
       'S300', 'Emgrand', '2131 Нива', 'Regata (138)', '103 ST2', 'EUT',
       '0-3-375L', 'Lead 90', 'S 315', 'EXC 250', 'T915', 'MX 200R',
       'SkyWave 650', 'CB 1000', 'HA', 'Corona', 'Lead 50 AF 48',
       'Magna 250', 'S338SH', 'Р4', 'YBR125', 'X10', 'Astra GTC', 'Neon',
       '740', 'Lioncel', 'MLT 735 LSU', 'CCS-GF', '164', 'FD 50QT',
       'Krokodile K-JC', '9758', 'Z 1000', '350 EXC-F', 'AZW', '8904',
       'O 403', '1140', 'Bull 200', '11.230', 'V90', 'AR S',
       'GSX 750F Katana', 'Burg', 'Menlo', 'V 250C', 'Starex', 'K2',
       '8352', '116', 'A13', 'SM5', 'O 303', '038', 'M 8000 Mountain',
       'TDM', 'O 309', 'MT 150-5', 'F 900R', 'LTM 1040', '2191 Granta',
       'BWP', '211 HD', 'Duke 125', 'ID.6', 'ST 1300 Pan European', '128',
       'Bobber', 'CGE 33', '3 Cross', 'NT 650V Deauville', 'Active',
       'CH1012L', 'QJ', '306', 'T815', 'C15', 'Dominar', 'VT 1100 Shadow',
       'Планета 4', '81021', 'RIB', 'ZS 250GS', 'Benelli TNT250',
       'Journey King', 'CBR 650F', 'Vue', '0-34-3 Fak', 'Спорт', 'V150A',
       '720 Cuddy SO', '56', 'Bigy', '2ПТС-4', '8103', '72', 'CBR 954RR',
       'WaveRunner', 'Forza 250', 'Mine', 'Try', 'XVS 950A Midnight Star',
       'Ultima', 'ADR Tanker', 'FZ6 N', 'XTZ 750 Super Tenere', 'Mollet',
       'Зерновоз', 'Plus', 'LF 150-8', 'Canoe', 'Merry Fisher', 'Via 50',
       '2ПН6', 'SNCO', '3151', 'Granada', 'ZT 310-V', 'S3363FR',
       'Юпітер 3', 'FT 300-C5C', 'K 1300GT', 'VX', 'Колхозник', 'TW',
       'TRX 500 Foreman', 'Discovery 4', 'SP-110', 'SZF 18', 'A-Series',
       'HSA', 'А-091', 'CF500', 'AW', 'Imperial', 'NC 750SD', 'X-Pro',
       'RK', 'ZWF 18', '3B0011', 'Tico', 'SD 200', 'Wolf', 'Dio AF-28',
       '368', 'Kayo', '750-141', 'Benni', 'Дорожник', 'ZS 250GY-3 (RX-3)',
       'Tact AF-51', 'CBR', 'SP 150S-17', '8527', 'MX-3', 'F500',
       'VN 1600', '3205', 'YB80QT-3 (Jog)', 'FTR', 'Super Cub 50',
       'FT 250', 'Fort 4', '704', '400 LC4-E', 'Т-200', 'Alfa МТ 125-8',
       'Indy', 'SP 110C-3WQ', 'SR3MEF', '5205', '12B', 'MT 125-8', '2400',
       'SMKV', 'Bali 50', '3160 Симбир', 'Vanette', '250 SX-F', 'Leopard',
       'NC 750S', '8551', '55PL1111FN07', 'SA 339K', 'GP', 'Gtle 250',
       'N 216', 'Axis', '360K110', 'VM 200-10', 'CRF 1100L Africa Twin',
       '12.163', 'LX 200', 'X Road', '625', 'SP 200R-25I', '390', 'Люкс',
       'Serena', 'J10', 'ER30', 'АЦПТ-0', 'Silver Wing 400', 'Vel Satis',
       'V 200', 'D-Tracker 250', '1400', 'N 313', '18.370', '3741',
       'MHPS', '126', 'VL 800 Intruder', 'Roadwin', 'Fuel Tanker', '535',
       '50 hp', 'Estima', 'Ski-Doo', 'Spyder', 'GrassTracker 250',
       'Pantheon 125', '545', '42', 'S-Coupe', 'CD381HB', 'MKS', 'Д',
       'Telluride', '93866', '4 Crossback', 'XXL', '62', '41',
       'Renegade 800', 'Jaguar', 'Super Duke 1290',
       'Sportsman XP 1000 High liftrer', 'Safari', 'Gold Wing F6B', 'E3',
       'ATL', 'BV', 'Tiburon', 'WR 125R', 'King', 'SH 300i',
       'Dyna Switchback', 'FX 50', 'FZX', '938662', 'Pro Mag', 'Dakota',
       'ПС', 'Flame 150', 'K-750', '973', 'CBR 600RR', 'LR', 'Wake',
       'Interstar', 'Magna 50', 'Urvan', 'Leeza', 'BPDA 10-18', '2310',
       'Wise', 'PR 732BM', 'B 220Z', 'HD 110', 'CCR', 'Gloria',
       'Breakout', 'DV 85', 'Convoy груз.', '6124Р4', 'Babetta', 'Z900',
       'Marea', 'Max 300', '6516V8', 'K 1300S', 'CRF 250RX', 'SP 200',
       '35.414', 'Vesta SW', 'DL 650', 'Vulcan 900', 'TP', 'GLP/GDP',
       'R 144', '165', 'Savana', 'FGF 42-7FGF20', 'Monster 696',
       'F 650GS', 'Xterra', '2500SCR', 'SC', 'SSi Sportboats', 'V65',
       '28N', 'Tipper LTD', 'CRF 1000L Africa Twin', '5.4', 'V-Strom',
       'NC', 'TXT Racing', 'EC', 'Adventure', '890 Adventure R', 'ADV',
       'Norden 901', 'TXT GP', 'SM', 'CB', 'CL 500', 'Vitpilen', 'Versys',
       'SV 650', 'NX 500', 'Duke', 'Enduro', 'Gold Wing', '18.320',
       'Pregio', 'Runner', 'HHR', 'E-HS9', 'X30L EV', '5207', 'П-3.5',
       'Panda Cross', '470', 'XR 600R', 'РМЗ-640', 'BL 61B', '8',
       'EuroTech', 'NW33ST', 'B37', 'WB', 'OVB', 'Tricker 250', 'Gaia',
       'Hypermotard', 'Dyna Super Glide', '183121', 'L 220E', 'D9', 'XA',
       '18.360', '30', 'FLC', 'CB 500X', '650108', 'ONCR', 'L 180',
       'Explorer 1800', 'Турист', 'SMR', 'XL 650', 'SC-3', 'Hardox', 'FL',
       'First', 'МТ125 (Dingo)', 'K 1300R', 'O 404', 'А-092Н2', '3B1057',
       'Slingshot', 'T', 'Novus', 'Today AF-61', 'Burgman 400',
       'KingQuad 500', 'California', 'GSR 750', 'FB', 'Address V50',
       'MP3', '5224В', 'Django', 'Himo T1 City', 'Voleex C10', 'KX-101',
       'XVS 650 Dragstar', 'PTL', 'RM 250Z', '65UJ', 'eVito', 'R6',
       '5224', 'T917 Acron', 'A-Max', 'T-Class', 'DR-Z 400SM',
       'Celebration', 'VM 250GY', 'Stilo', 'DV', 'Idea', 'Courier',
       'Virago', 'Jet', 'NS-1', 'Storm 80', 'Brute Force', '15М',
       'KXF 450 Racing', 'Compact 12', 'S380', 'Atos', '1404', '743',
       'RX 70-16T', '5FG20', 'KPV', 'XVS 1300 Midnight Star',
       '300 Advance', 'Street', 'Traxter', 'Apache RR310', 'Sea-Doo',
       'Mana 850 GT', 'UForce', 'TNT 302S', 'N 212', 'EuroStar', 'FFB',
       'SD 27', 'Racer', '3163', 'Aumark', '02-8FGF20', 'TG', 'PL 400',
       'SH 150', 'Titan', 'FZ-S', 'K4', '1299 Panigale S', 'General',
       'Rockster', 'ADX', 'X-Line', '49', 'Tourino', '25.422', '534',
       'CVO Road Glide', 'S450', 'ATI', 'SKHL', 'A 112', 'AZ',
       'Ninja 400', 'RVR', 'TDM 850', '93G', 'Speedfight', 'OPL',
       'Fiat 500', 'Burgman', 'A450L', 'Summit', 'Atto 3', 'Fuel Tank',
       'Maxus', 'R', 'Drag Star 650', 'Symphony', 'YB 150T-15D UP',
       'X9 500', 'Q2L e-tron', 'Z-210', '35', 'Pan America', 'Fat Bob',
       'Fat Boy', 'Nightster', 'FLTRXS', 'Softail Standard',
       'Low Rider\t', 'GSF 600 Bandit S', 'E10-14C', 'N 116', 'N-36',
       'XLR 200R', 'Юпітер 2', '8050', 'DPU', '19.403', 'Sebring',
       '1230ES', '919', 'CA', 'X-Road 250СВ', 'City', '376П', '6014',
       '3250', 'Viseon C10', 'Comansa', 'DF-25', 'Fiat 595', 'GN 125',
       '380К911', 'Citigo', 'R Series', '3503', 'X-Trail 200', '5516',
       'N Series', 'X8R-S', '500 Elite', '310 Sundancer', '2150 REIO',
       'HD', 'MPS', 'МТ 1435', '2625', 'Rohr', 'Sanh Plane',
       'Jog Artistic', 'ММВЗ-3.115', '10', 'F50', '565', 'Alfa',
       'BW 174AD', 'TRX 650 Rincon', '65', '370', 'ZS 200A', 'N 4407',
       'Futura FHD', 'Century', '5М', 'AquaTrax', 'GranTurismo', '144',
       'Rocky', '34-FK', 'M 150', 'D6R', 'D 65EX', 'LH 500', 'ЗИЛ',
       'DR 650', '8138', 'Logan Van', 'Jogger', 'RF 400RV', 'SJ',
       'Victor Suv', 'Besta', 'Glastron', 'FT 250GY-CBA', 'Bayside 765',
       '155', '211-H', 'XY 200GY', '837810', '504', 'V 125P', 'H 100',
       'Capella', 'Sanz', 'Clicke', 'A18L', 'Fox', '150СС', 'ППЦ-30',
       '610', 'Concerto', '2411', 'СПВ-17', 'Speedster', '5208', 'FX 45',
       'Alga', '3162 Симбір', 'Falcon', 'Forman', 'SV 400', 'Basic Jog',
       'L 400', 'Херсонка', 'ZX 14', 'LF пас', 'C25', 'Santana', 'Gotha',
       'Lokotrack', 'CT 50', 'UL', 'ML 50-8CH', 'GSX 650F',
       'KP200 (Irokez)', 'T4', 'BoatKing', 'FLHTK', 'BLS', '3411',
       'Pro Guide', 'ASC', 'VFR 800', 'Saxo', 'Colibri', '11.180',
       '13 Чайка', 'SMR 450', 'Юпітер 4', '821', 'G970', 'H 25D',
       'F 156A', '8.136', '244', 'S363EL', 'ZM15', 'iXtrack', 'K 1600B',
       'CR 250R', 'ЕК-12', 'Magnus', 'Leone', 'M 1000RR', 'ZZR 400-2',
       'Grand Axis', 'Lead 100', 'А-144.3', 'YS', 'А 074 Эталон', 'м',
       'Musa', '43105', 'P7', 'SNCC', '3.5TT', 'S43EDD', 'Lets',
       'Jog SA12', 'TRX 680 Rincon', 'ММ', 'Cruise', 'K', 'Mystic',
       'MCO-48', 'CityR', 'OH-Series', 'Silver Wing GT 600', 'SP 150R-12',
       '121', 'МТ-10-36', 'ML 200', 'Drive', 'K 1600GTL', 'CBR 600F4i',
       '1340 Electra Glide', '2350', 'H 300', 'FQ', 'Mark VIII',
       'ECR 50D', 'Monster 797', '11.190', '22', 'YWE', 'DLPS', 'Sana',
       '250 СR', 'Senator', '350 Classic', 'BL', 'Justy', '317 HDH', 'АМ',
       'Topic 50 AF-38', 'YXZ 1000R', 'X-Star', '2252', 'Chase', 'XT6',
       'Q4 Sportback e-tron', 'EX 300', 'TXL', 'Seicento', 'GP 1200',
       'Skipper', 'CB 900F Hornet', 'T911', 'T34C', 'F450L',
       'Cross Country', '53208', 'N 516', 'AE', 'XSJ', '2125 Комби',
       'NT 700V', '551605', 'VN', 'Fluence Z.E.', 'Pulsar RS200',
       'Madison', 'Samand', 'ATV 125', 'NAT', '856100', 'Sprite',
       'VS.Mont.Sro', 'Lumina', 'PR', '5551', 'V250 VXR', '328', 'S KZZ',
       '23.403', '1304', 'SR34ES', 'Y', '205SH', 'М-343 SМ', 'e-Berlingo',
       'GTX-F', '1-2', 'N 4411', 'XF 650 Freewind', 'MT110-2', 'ASW',
       'EN', 'DS 200', 'KLR 650', '3B2014', '0502Т', 'ZT', 'ZT G155 U',
       '565Li', 'GP1 400', 'Assault', 'Target', 'Silver Wing GT 400',
       'SV 650SF', '9397', 'F 800R', '1044', '3962', '19.464', '9380',
       'LF 250-D', 'F-350', 'OPK', 'LF200-10S (KPR)', 'Ideal', 'Shark II',
       'MR2', 'CBF 600SA', 'YH', 'ПП-5', '315 HDH', '8155-02', 'EL',
       'Elystar', 'Silver Wing 600', '3STT', 'Tiida Latio', 'Gt Trailor',
       'Sigma', 'VN 1700', '642205', 'UK', 'Ninja 600 ZX-6R', 'АГП', 'VS',
       'X-City', 'Ride', '3250 Антон', '270 CR', 'Terra-X 250 Road',
       '980', '240', '9996', '16', 'S339CX', 'VTR 1000F', 'CHS 125', 'RF',
       'Laweta', '9976', 'X60', '36SN12', 'Blaster', 'RM-Z 450', 'Acron',
       'CrossEastar', 'YB 125T-12', 'Routan', 'ZKI 18-4.9', 'FT-200',
       'MT 110-2', 'W6', 'Yesterday', 'Burn', 'GN', '6501А8', '9357',
       'AWF 18', 'SP 150-28', 'CSP', 'Junior', 'ПА', 'МТ-11', 'Mago',
       '21', 'SAPL', 'ZL 50', '318', '43253', 'ER', 'e-Jumpy',
       'VFR 800F Interceptor', 'Vision Tour', 'Stryker', '5510', 'S 417',
       '250 Advance', 'Golf Sportsvan', 'KP 150', 'Softail Deluxe',
       '6129', 'SLR 650', 'SM 610', 'RS', 'LX 300GY-A', 'Ninja 636 ZX-6R',
       '1198', 'Cube', '696', 'Monza', 'FZ 25', 'MT 150 Region',
       'Classic', 'KHKS', 'А-0921 (Е-3)', 'MB-Class', 'BT-50',
       'T917 Astron', '21L', 'Streetwise', 'T918', 'Biz 125', 'EC 480DL',
       'Original', 'Super Light', 'ZS 150J', 'DHKS', 'С-382', 'WR 450F',
       'MLT-X 1035 LT LSU', 'Robuste', 'Z 400', 'Intruder 1500', 'F 111P',
       'Pride', 'Aprio', 'ER-5', 'Columbia', 'Solterra', 'S343',
       'KX 61-3', 'XG', '1121F', 'F 800GS', 'Scarabeo', '81024',
       '200 Sundeck', 'EX 37', 'Schutz', '11.220', 'SP 300T-1', '41.464',
       'Verta 200', 'CBF 500', 'Giorno AF-24', 'Avella',
       'NTV 650 (Revere)', 'N300', 'SNBS', '817', 'B8R', 'Berkhof', '543',
       'Vista', '122', 'Astromega', 'SP 200R-30', '334', 'TDWG65Z/T3',
       'LH', 'K19', 'T5', '30РМ1100', '25РМ1101О', 'Crox', 'Прогресс',
       '33.322', 'Astron', 'Gator', 'Pitbull', 'HMK 102S', 'HMK 102B',
       'HMK 102B Supra', 'HMK 220LC', 'HMK MG 600', 'C7H', 'BPC100',
       'BLK02-E', 'TGA 300', 'ZT G155 U1', '250 RR', 'Rival', '50A',
       'GTY320', 'T120', 'GTY160', 'GTY220', '956GT', 'V-Strom 1000',
       'Fukang ES600', 'EF', 'NS34KT', 'JJ', 'V-Rod', '690', '14 Чайка',
       'Fairlane', 'SLG', 'Ninja 300', 'MT 125-2B', '14.264', 'Z 250SL',
       '14.285', 'SX 125', 'Aquila 650', 'R 1100R', 'Mirofret', 'Niagara',
       '65711', '12.220', '527-58', '5335']))
    year = st.number_input('Рік', 1900)
    equipment = st.selectbox('Специфікація', [None] + sorted(['Base', 'M Package', 'S-line', 'Premium', 'AMG Package',
       'S-Line', 'Elegance', 'Prestige', 'Style', 'Invite', 'L&K', 'Pro',
       'Pure+', 'Prestige+', 'Individual', 'Premium+', 'Allure', 'Style+',
       'Comfortline', 'R Line', 'Sport&Style', 'Luxury+', 'Prime',
       'Business', 'Comfort', 'Sportline', 'R-Line', 'Luxury Line', 'SE',
       'AMG Line', 'Exclusive', 'Vogue', 'Ambience', 'Comfort+', 'SL',
       'Tekna + Winterpaket', 'SEL', 'Lounge', 'F Sport', 'Highline',
       'Premier', 'M Sport', 'Full', 'Touring', 'Bose', 'SV',
       'SEL Premium', 'Trend', 'EX-L', 'Top', 'Latitude Plus', 'Tekna',
       'AMG-Line', 'Executive Lounge', 'SV Autobiography', 'Sport Life',
       'Avantgarde', 'Executive', 'Active', 'Bulli', 'Longitude',
       'Terrain Tech', 'GT', 'Limited', 'Ambition', 'Komfort Edition',
       'Platinum Edition', 'Luxury', 'Sport', 'Live', 'HSE', 'Drive',
       'Latitude', 'AMG Style', 'Summun', 'Intense', 'Shine',
       'Momentum Pro', 'Black Label', 'R-Dynamic S', 'Acenta', 'R-Design',
       'Executive+', 'Ultimate', 'Premium R-line', 'S', 'Life',
       'Trailhawk', 'RS', 'Touring S', 'Ambiente', 'XLE', 'Edition 1',
       'SXT', 'Titanium', 'GL', 'Sport Line', 'LE', 'R-design',
       'Autobiography Dynamic', 'M-Package', 'Momentum', 'Performance',
       'Ultimate Dark', 'Advanced', 'Edition', 'JLX-E', 'Zen', 'Lite Pro',
       'Inscription', 'Clever', 'Express', 'Autobiography', 'Basis',
       'N-Connecta', 'EX', 'X-Perience', 'Luxe Essential', 'R-Sport',
       'Ultimate-e', 'mid', 'Adventure', 'R-Line Platinum+', 'Urban',
       'Artico', 'Siv', 'Limited Edition', 'Dynamic Version', 'Goal',
       'Acenta Safety', 'Excellent', 'Black Edition', 'Pure', 'Cosmo',
       'Premium Life', 'Summum', 'TRD Pro Series', 'Grand Touring',
       'Top Panorama', 'First Edition', '21104-812', 'Security',
       'G Manufaktur', 'Luna', 'Executive Edition', 'Rubicon Unlimited',
       'SL Plus', 'Nismo RS', 'Premium R-Line', 'X-Dynamic',
       'Plus Bright', 'R-Dynamic SE', 'City', 'Recharge R-Design',
       'M Sport Package Pro', 'Executive Life', 'SE* Sport', 'Crossroad',
       'Executive plus', 'Standard+', 'Lux', 'F-Sport', 'Ludicrous',
       'Design', 'GT-Line', 'Стандарт', 'CDX', 'Entry', 'DLX-1',
       'Hi-tech (Black quartz)', 'Cinquecento', 'Active+', 'HSE Dynamic',
       'Premium Panorama', 'top plus plus', 'LE Style Navi', 'Classic',
       'Special Edition', 'Cargo 5-Seat', 'Titanium S', 'Amb Plus',
       'Essentia*', 'Ultimate+Navi', 'Edition 80', 'Mid', 'Active Pack',
       'TF699P01', 'III Authentique', 'Advance Package', 'SX', 'Hi-Tech',
       'LTZ', '2110-4', 'Designo', 'CD95 EAQ', 'Bose Panorama', 'Ghia',
       'Life+', 'Browstone', 'Signature', 'G', 'Feel', 'Ninja', 'xLine',
       'Autobiography  Black Limited Edition', 'Sport+', 'GL+', 'Instyle',
       'TRD Sport', 'Dynamic Plus', 'Touring+', 'Nismo',
       'Premium EAL/EAM', 'Zen+', 'Ambiente Plus', 'Lounge plus',
       'Premium Edition', 'SE Dynamic', 'Dolcevita', 'ST', 'Basic',
       'Xperience', 'GT-Sport', 'SR', 'Portfolio', 'Trend & Fun',
       'Laureate', 'Premium Plus', 'X-Dynamic SE', 'Platinum',
       'GT Performance Edition', 'LT Black', 'High Luxury', 'Sport+Navi',
       'ECO', 'LT', 'Тор', 'Vogue HSE', 'GLI', 'Люкс', 'Top Plus', 'GLS',
       '360', 'Dynamic', 'Trendline', 'Tendance', 'XS',
       'Premium Prestige', 'Drive plus', 'GLX', 'Team', 'LS',
       'Sport & Style', 'R-Design Momentum', 'Status Life', 'Hightline',
       'Creative', 'YH', 'SE+', 'top plus', 'Type S', 'Dinamic',
       'SE Sport', 'Le Kozak', 'Luxe', 'Scout', 'Acenta Parking',
       'Rallye', 'CG25 EAC', 'Elite', 'III Dynamique', 'R-Dynamic',
       'TF69YP22', 'Sound', 'HSE Luxury', 'Joy', 'XLE RedWood', 'Touareg',
       'STD-1', 'Confort Pack', 'Techno', 'Premium 70th Anniversary',
       'SE*', 'Business Life', 'R/T', 'TF696P40', 'Quadreat Magno-Matt',
       '2HY', 'Comfort +', 'Ludicrous+', 'Elegance  A', 'YF Comfort',
       'Excellence', 'Initial Paris', 'F-Type', 'Manufaktur', 'Essentia',
       'Touring +', 'Ambiance', 'M18', '2112-1', 'Stingray Z51',
       'Superior', 'FR', 'LE  F-6', 'Premium plus Navi', 'Норма',
       'Future Life', 'N-Connecta Parking', 'Sport + Navi', 'Standard',
       'TF69Y1-28', 'Trail Hawk', 'STD', 'Premium+Navi',
       'Technology Package', 'Premium (GKH6 EAF)', 'TF48Y229 YP20',
       'LE  F-DG', 'Elegance+', 'Business+', 'Premium Business',
       'Technology', 'Enjoy', '110-30', 'Exclusive Manufaktur', 'Opera',
       'Authentique', 'Ocean Race', 'Reserve', 'Launch', 'DOHC ND16',
       'Miyata', 'Lux  TA69W0', 'Zero Edition', 'AMG Designo',
       'Outdoor GL+', 'Premium +', 'SE Navi', 'JLX-EL',
       'Touring Black Edition', 'Summit', 'Premium + Navi', 'XT',
       'M-Sport', '140-40', 'Expression', 'Rodeo', 'XSE', 'SLX', 'sport',
       'Kinetic', 'PA', 'Ecoboost', 'Overland', 'Premium Navi',
       'Classic Active', 'R/T Scat Pack', 'Тор Panorama', 'Winner 25',
       'Rivoli', 'Trend+', 'GT Line', 'Trend Edition', 'Hi-Tech+', 'TX L',
       'Premium Luxury', 'Enjoy High', 'top', 'Comfort Life', 'GoaL',
       'E-type version', 'Unique Life', 'Shiro', 'E-chi version',
       'Premium EAA/EAB', 'Visia', 'Join', 'Special', 'Premium Tech',
       'Ministry of Sound', 'Mid (EAC)', 'Edition+', 'Cup', 'Diesel',
       'GT Line+', 'Standart', 'AVG', 'Saksonia', 'SR Black Edition',
       'Pop', 'Launch Edition', 'NS', 'Green Line', 'Reference', 'Plus',
       'Top Brown', 'Luxury Edition', 'Invite +', 'Allure Pack',
       'Sport Chic', 'GranSport', 'Edition One', 'ST-Line',
       'Classic plus', 'Mid plus', 'LX', 'Touring (BHD6 EAC)', 'VC',
       'Edition High', 'Style +', 'Tekna +', 'Impress', 'Classic+',
       'Supercharged Vogue SE', 'S-Edition', '63', 'Rubicon', 'mid (EAD)',
       'TF698К20', 'Premium Brown', 'Conceptline', 'Luxury plus',
       'Sahara', 'R-Dynamic Base', 'R-Line Platinum', 'VA', 'Tour',
       'Vogue SE', 'Touring EAH', 'Ambient',
       'Bose Personal Edition Orange', 'MX 18', 'Street', 'II',
       'EcoBoost', 'Ambiance +', 'Essential', 'RJ', 'Driver', '1HY',
       'Evo Dinamic', 'Basic Plus', 'Ultimate Bright', 'SV2',
       '100 Years Edition', 'Performance Line', 'SE Style Navi',
       'Basic plus', 'So Chic', 'Hi-tech', 'Comfort5 ESP', 'E-Border',
       'Cosmo Mid', 'Plus Dark', 'Innovation', 'Executive+Navi', '110-34',
       'Xcellence', 'Live Pack', 'Premium + Roof Rail', 'R',
       'Premium Sport Pack', 'Dynamique Pack1', 'Rex', 'Select',
       'D5MК550', 'Wildtrak', 'Advance', 'Top ++', 'TF696P41', 'TF69Y226',
       'LE-D', 'ST2', 'Optima Audio', 'Vitamin', 'StarTeam', 'High',
       'Base plus', 'Injection', 'Classic Active Plus', 'Trenline',
       'M 19', 'LT+', 'Laredo', 'NG  Life', 'SK9ALEL', 'SE plus',
       'Rubicon X', 'Ultra Luxury', 'Grand Chic', 'Аmbition',
       'Momentum 5', 'Allure-Line', '4I Limited', '134-30', 'TF69C168',
       'Touring plus (BHD8 EAB)', 'Premium+Panorama', 'Legacy (ZS)',
       'M LOW COST', 'Luxe ProActive', 'Style Passion', 'Black&Silver',
       'Comfort A', 'Tech', 'Volcano', 'STD3 ESP', 'X', 'YF Top', '4J',
       'DLX-2', 'L', 'Classic  plus', 'AC-GE-CK-CMД', 'Elegant',
       'Intense LE', 'DLX-3', 'Acenta Parking+Navi', 'LTZ +',
       'Attraction', 'Track', 'M30', 'Access', 'TF69YP23',
       'Elbrus Edition', 'LE Intense', 'Top Navi', 'SDLX', 'V8',
       'Sports (EAJ)', 'Blue', 'III Expression', 'EX Premium', 'LT2',
       'Passion', 'Greenline', 'American Classic Edition', 'Beats',
       'MX 30', 'TF699P71', 'VIP Business DizaynVIP', 'Xclusive', 'XE',
       'Comfort  Plus', 'Style Safety', 'Ultramarine', '116-30', 'Match',
       'GR Sport', 'Executive Navi', 'OPC', 'EAL', 'Mid+', 'Touring EAG',
       'TF EyeSight', 'Luxury AFB', 'DLX', 'Easy', 'Touring XT', 'VR',
       'Active Base', 'M Performance', 'Autobiography Ultimate Edition',
       'Spirit', '2LT', 'Hybrid4', 'GT Pack', 'Top plus',
       'Luxe Proactive', 'North', 'Family', 'N-Style', 'Acenta Navi',
       'Elegance Life', '4D', 'Dream', 'CD89 EB3', 'N-Design', 'USA EX-L',
       'Luxury  plus', 'VIP Panorama Brown', 'R-Dynamic HSE', 'SS',
       'E-environment version', 'Track &amp; Style', 'JCW', 'Sol +',
       'Acenta Safety+Navi', 'Luxury VIP5', 'Inform', 'LT1',
       'Premium+NAVI', 'Optima', 'Trace Life', 'Combi Elegant', 'SK9ALFL',
       'Shine Pack', 'GS Trophy', 'Sport  S11', 'Soft Top']))
    mileage = st.number_input('Пробіг', 0)
    place = st.selectbox('Місто', sorted(['  Одеса', '  Кривий Ріг', '  Канів', '  Запоріжжя', '  Київ',
       '  Львів', '  Полтава', '  Рівне', '  Херсон', '  Черкаси',
       '  Івано-Франківськ', '  Дніпро (Дніпропетровськ)', '  Луцьк',
       '  Миколаїв', '  Хмельницький', '  Чернівці', '  Вінниця',
       '  Харків', '  Балаклія', '  Мостиська', '  Трускавець', '  Стрий',
       '  Бердичів', '  Тульчин', '  Тернопіль', '  Кременчук',
       '  Виноградів', '  Житомир', '  Камінь-Каширський', '  Суми',
       '  Костопіль', '  Буськ', '  Бершадь', '  Мукачево', '  Ужгород',
       '  Коломия', '  Умань', '  Ізмаїл', '  Нововолинськ', '  Дрогобич',
       '  Бровари', "  Білогір'я", '  Городок', '  Тячів', '  Буча',
       '  Ратне', '  Дубно', '  Броди', '  Жовті Води',
       "  Кам'янське (Дніпродзержинськ)", '  Васильків', '  Ковель',
       '  Біла Церква', '  Кропивницький (Кіровоград)', "  Міжгір'я",
       '  Бориспіль', '  Рокитне', '  Гайворон', '  Коростень',
       '  Самбір', '  Долина', '  Чортків', '  Первомайськ',
       '  Южне (Південне)', '  Радивилів', '  Кременець', '  Іршава',
       '  Звягель', '  Переяслав', '  Олександрія', '  Червоноград',
       '  Млинів', '  Золочів', '  Новоукраїнка', '  Монастирище',
       '  Сарни', '  Краматорськ', '  Шепетівка', '  Козятин', '  Калуш',
       '  Христинівка', '  Чернігів', '  Полонне', '  Вижниця',
       '  Вишгород', '  Павлоград', '  Новомосковськ', '  Дружківка',
       '  Обухів', '  Красноград', '  Жовква', '  Володимир-Волинський',
       '  Чигирин', '  Рава-Руська', '  Радехів',
       '  Білгород-Дністровський', '  Охтирка', '  Лозова', '  Мена',
       '  Ірпінь', '  Ватутіне', '  Бар', '  Волочиськ', '  Бережани',
       '  Свалява', '  Вознесенськ', '  Вишневе',
       '  Софіївська Борщагівка', '  Шостка', '  Славута',
       '  Богородчани', '  Зміїв', '  Старокостянтинів', '  Надвірна',
       '  Яготин', '  Гнівань', '  Летичів', '  Новоархангельськ',
       '  Славутич', '  Острог', '  Сміла', '  Боярка', '  Теофіполь',
       '  Сокаль', '  Романів', '  Олевськ', "  Кам'янець-Подільський",
       '  Хуст', '  Бучач', '  Моршин', '  Гайсин', '  Жашків', '  Хотин',
       '  Фастів', '  Сколе', '  Ніжин', '  Арциз',
       '  Благовіщенське (Ульяновка)', '  Велика Михайлівка',
       '  Покровськ (Красноармійськ)', '  Дунаївці', '  Кагарлик',
       '  Жидачів', '  Подільськ (Котовськ)', '  Великий Березний',
       '  Новояворівськ', '  Чорноморськ (Іллічівськ)', '  Прилуки',
       '  Могилів-Подільський', '  Коростишів', '  Болехів',
       '  Южноукраїнськ', '  Балта', '  Хорол', '  Велика Багачка',
       '  Нікополь', '  Яворів', '  Бурштин', '  Турійськ', '  Яремче',
       '  Борислав', '  Ромни', '  Заліщики', '  Берегове', '  Горохів',
       '  Малин', '  Пирятин', '  Лубни', '  Вараш (Кузнецовськ)',
       '  Українка', '  Чемерівці', '  Чечельник', '  Теплик',
       '  Ізяслав', '  Овруч', '  Збараж', '  Шаргород', '  Тисмениця',
       '  Рогатин', '  Мерефа', '  Варва', '  Овідіополь', '  Косів',
       "  Кам'янка-Бузька", '  Дергачі', '  Бородянка', '  Снятин',
       '  Бобровиця', '  Жмеринка', '  Новий Розділ', '  Ківерці',
       '  Корець', '  Заставна', '  Кобеляки', '  Немирів', '  Гостомель',
       '  Добропілля', '  Підворки', '  Конотоп', '  Лебедин',
       "  Слов'янськ", '  Ярмолинці', '  Новодністровськ',
       '  Компаніївка', '  Галич', '  Красилів', '  Кролевець',
       '  Синельникове', '  Новий Буг', '  Костянтинівка', '  Куликівка',
       '  Макарів', '  Роздільна', '  Хмільник', "  Кам'янка",
       '  Нова Одеса', '  Ходорів', '  Борщів', '  Березне',
       '  Верховина', '  Звенигородка', '  Славське',
       '  Корсунь-Шевченківський', '  Горішні Плавні (Комсомольськ)',
       '  Богуслав', '  Окни (Красні Окни)', '  Здолбунів', '  Любомль',
       '  Аули', '  Ружин', '  Покров (Орджонікідзе)', '  Сторожинець',
       '  Любашівка', '  Перещепине', '  Першотравенськ', '  Гадяч',
       '  Болград', '  Глобине', '  Тростянець', '  Глибока',
       '  Миронівка', '  Баришівка', '  Кілія', '  Буковель',
       '  Мирноград (Димитров)', '  Зборів', '  Врадіївка', '  Іванків',
       '  Перемишляни', '  Софіївка', '  Нетішин', '  Шацьк',
       "  Знам'янка", '  Рахів', '  Сокиряни', '  Пустомити',
       '  Старий Самбір', '  Турка', '  Шишаки', '  Миргород',
       '  Богодухів', '  Соснівка', '  Нова Ушиця', '  Карлівка',
       '  Петропавлівська Борщагівка', '  Маневичі', '  Біляївка',
       '  Попільня', '  Володимирець', '  Світловодськ', '  Золотоноша',
       '  Ладижин', '  Кіцмань', '  Радомишль', '  Березнегувате',
       '  Калинівка', '  Оржиця', '  Березань', '  Долинська',
       '  Крюківщина', '  Погребище', '  Носівка', '  Остер',
       '  Воловець', '  Ржищів', '  Ізюм', '  Баштанка', '  Козелець',
       '  Гореничі', '  Нова Водолага', '  Борзна', '  Кодима',
       '  Томашпіль', '  Новомиргород', '  Крижопіль', '  Рожнятів',
       '  Шумськ', '  Вільнянськ', '  Верхівцеве', '  Віньківці',
       '  Тернівка', '  Чуднів', '  Чугуїв', '  Лопатин', '  Кегичівка',
       '  Баранівка', '  Монастириська', '  Копичинці', '  Валки',
       '  Стебник', '  Іванівка', '  Голованівськ', '  Піщанка',
       '  Ставище', '  Краснокутськ', '  Любар', '  Рожище', '  Чутове',
       '  Апостолове', '  Теребовля', '  Глухів', '  Марганець',
       '  Гребінка', '  Петрове', '  Єлизаветівка', '  Васильківка',
       '  Тлумач', '  Городенка', '  Тараща', '  Саврань', '  Лохвиця',
       '  Чорнобай', '  Покровське', '  Іллінці', '  Петропавлівка',
       '  Іваничі', '  Миколаївка', "  П'ятихатки", '  Гоща', '  Тетіїв',
       '  Ланівці', '  Семенівка', '  Білозерка', '  Лисянка',
       '  Сновськ (Щорс)', '  Деражня', '  Сквира', '  Кельменці',
       '  Хорошів (Володарськ-Волинський)', '  Пулини (Червоноармійськ)',
       '  Верхньодніпровськ', '  Володарка', '  Решетилівка', '  Локачі',
       '  Липова Долина', '  Бахмач', '  Зарічне', '  Ємільчине',
       '  Томаківка', '  Сарата', '  Андрушівка', '  Криве Озеро',
       '  Чубинське', '  Солоне', '  Захарівка (Фрунзівка)', '  Тальне',
       '  Нова Борова', '  Селидове', '  Ямпіль', '  Брусилів',
       '  Близнюки', '  Підгайці', '  Черняхів', '  Чоп', '  Новоселиця',
       '  Шарівка', '  Гусятин', '  Козова', '  Межова', '  Сахновщина',
       '  Білопілля', '  Рудки', '  Ананьїв', '  Татарбунари',
       '  Новгород-Сіверський', '  Олександрівка', '  Буринь',
       '  Берестечко', '  Демидівка', '  Котельва', '  Нові Санжари',
       '  Мала Виска', '  Люботин', '  Знаменівка', '  Добровеличківка',
       '  Первомайський', '  Шевченкове', '  Пісочин', '  Козельщина',
       '  Димер', '  Маріуполь', '  Березівка', '  Муровані Курилівці',
       '  Курахове', '  Недригайлів', '  Арбузинка', '  Липовець',
       '  Теплодар', '  Сосниця', '  Дубровиця', '  Ічня', '  Оріхів',
       '  Південне', '  Червоний Донець', '  Стара Вижівка', '  Машівка',
       '  Путила', '  Городище', '  Лиман (Красний Лиман)', '  Рені',
       '  Літин', '  Вільногірськ', '  Зеленодольськ', '  Тарутине',
       '  Лозуватка', '  Олешки (Цюрупинськ)', '  Бахмут (Артемівськ)',
       '  Ворохта', '  Перечин', '  Снігурівка', '  Зачепилівка',
       '  Шпола', '  Оратів', '  Ріпки', '  Барвінкове', '  Каланчак',
       '  Поляна', '  Царичанка', '  Маньківка', '  Нові Петрівці',
       '  Згурівка', '  Зіньків', '  Срібне', '  Петриківка',
       '  Братське', '  Талалаївка', '  Любешів', '  Путивль',
       '  Богданівка', '  Новогродівка', '  Єланець', '  Новгородка',
       '  Алчевськ', '  Веселинове', '  Корюківка', '  Магдалинівка',
       '  Казанка', '  Велика Олександрівка', '  Стара Синява',
       '  Мелітополь', '  Ширяєве', '  Диканька', '  Новотроїцьке',
       '  Березанка', '  Краснопілля', '  Вилкове', '  Коблеве',
       '  Дмитрівка', '  Городня', '  Просяна', '  Народичі',
       '  Доманівка', '  Бобринець', '  Очаків',
       '  Доброслав (Комінтернівське)', '  Васищеве', '  Саливонки',
       '  Тарасівка', '  Драбів', '  Герца', '  Гуляйполе', '  Короп',
       '  Підволочиськ', '  Лугини', '  Кринички',
       '  Торецьк (Дзержинськ)', '  Тиврів', '  Катеринопіль',
       '  Онуфріївка', '  Драгобрат', '  Вовчанськ', '  Широке',
       '  Великий Бурлук', '  Вільшанка', '  Чорнухи', "  Куп'янськ",
       '  Новомиколаївка', '  Черкаське', '  Устинівка',
       '  Велика Писарівка', '  Розівка', '  Макіївка', '  Приморськ',
       '  Печеніги', '  Пересічне', '  Фурси', '  Святопетрівське',
       '  Катюжанка', '  Нововоронцовка', '  Буди', '  Мала Данилівка',
       '  Старобільськ', '  Іршанськ', '  Каховка', '  Краснопавлівка',
       '  Високопілля', '  Генічеськ', '  Середина-Буда', '  Солоницівка',
       '  Бабаї', '  Слобожанське (Ювілейне)']))
    description = st.checkbox('Є опис')
    accident = st.checkbox('Був у аварії')
    engine_power = st.number_input('Кількість к.с.', 0)

    if st.button("Отримати передбачення"):
        mean_price = int(mean_prices['price'][mean_prices['mark'] == mark])
        features = [[mark, model, year, equipment, mileage, place,
                  description, accident, mean_price, engine_power]]
        data = {'mark': mark, 'model': model, 'year': year, 'equipment': equipment,
                'mileage': mileage, 'place': place, 'description': description,
                'accident': accident, 'mean_price': mean_price, 'engine_power': float(engine_power)}
        print(data)
        df=pd.DataFrame([list(data.values())], columns=['mark', 'model', 'year', 'equipment', 'mileage', 'place',
                  'description', 'accident', 'mean_price', 'engine_power'])
        

        category_col = ['mark', 'model', 'equipment', 'place']
        for cat, enc in encoder_dict.items():
          if cat in category_col:
              encoder = encoder_dict[cat]
              df[cat] = encoder.transform(df[[cat]]).reshape(-1, 1)
   
        features_array = df.values

        prediction = lgb_model.predict(features_array)

        output = int(prediction[0])

        st.success('Оракул каже, що така машина коштуватиме ${}. Успіхів! :car:'.format(output))


if __name__ == "__main__":
    run()
